use gnx_syed;
DELETE FROM `czareasterceros`;
DELETE FROM `czareas`;
DELETE FROM `czautfacturacion`;
DELETE FROM `czcargoemp`;
DELETE FROM `czcartera`;
DELETE FROM `czcentrocosto`;
INSERT INTO `czcentrocosto` (`Codigo_CCT`, `Nombre_CCT`) VALUES ('IPS', 'IPS DOMICILIARIA');
DELETE FROM `czempleados`;
DELETE FROM `czinvsolfarmacia`;
DELETE FROM `czproveedores`;
DELETE FROM `czradicacionescab`;
DELETE FROM `czradicacionesdet`;
DELETE FROM `czsedes`;
INSERT INTO `czsedes` (`Codigo_SDE`, `Nombre_SDE`, `Codigo_AFC`) VALUES ('1', 'IPS', '1');
DELETE FROM `czterceros` WHERE  `Codigo_TER` not in ('1','0');
UPDATE `cztipocontratos` SET `Nombre_TCL`='CONTRATO DIRECTO' WHERE  `Codigo_TCL`='01' AND `Codigo_DCD`=0;
DELETE FROM `cztipocontratos` WHERE  `Codigo_TCL`='02' AND `Codigo_DCD`=0;
DELETE FROM `czturnosdet`;
DELETE FROM `gxadmision`;
DELETE FROM `gxcontratos`;
INSERT INTO `gxcontratos` (`Codigo_EPS`, `Codigo_PLA`, `Codigo_TAR`) VALUES ('0', '3', '0');
DELETE FROM `gxegresos`;
DELETE FROM `gxeps` WHERE  `Codigo_EPS`<>'0';
UPDATE `gxeps` SET `FechaFin_EPS`='5015-12-31' WHERE  `Codigo_EPS`='0' AND `Codigo_DCD`=0;
DELETE FROM `gxfacturas`;
DELETE FROM `gxmanualestarifarios` WHERE  `Codigo_TAR`<>'1' ;
DELETE FROM `gxmedicos`;
DELETE FROM `gxmedicosesp`;
DELETE FROM `gxordenesdet`;
DELETE FROM `gxordenescab`;
DELETE FROM `gxprocedimientosdet`;
DELETE FROM `gxtarifas` WHERE  `Codigo_TAR`<>'1';
DELETE FROM `hcantecedentes`;
DELETE FROM `hcdiagnosticos`;
DELETE FROM `hcfolios`;
DELETE FROM `hcmedpacientes` ;
DELETE FROM `hcnotas`;
DELETE FROM `hcordenesmedica`;
DELETE FROM `hcordenesservicios` ;
DELETE FROM `hcsignosvitales`;
UPDATE `hctipos` SET `Activo_HCT`='0' WHERE  `Codigo_HCT`<>'ENFERMERIA';
DELETE FROM `hctratamiento`;
DELETE FROM `hcusuarioshc`;
DELETE FROM `hc_ENFERMERIA`;
DELETE FROM `hc_EVOL1`;
DELETE FROM `hc_HC01`;

DELETE FROM `hc_NNUTRI`;
DELETE FROM `hc_NPSICO`;
DELETE FROM `hc_TFEVOL`;
DELETE FROM `hc_TFIS1`;
DELETE FROM `hc_TFONEV`;
DELETE FROM `hc_TOCU1`;
DELETE FROM `hc_TOEVOL`;
DELETE FROM `hc_TRESP1`;
DELETE FROM `hc_TREVOL`;

DELETE FROM idplantillas WHERE Codigo_TER<>'1';
DELETE FROM `itauditoria` ;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ADM' AND `Tabla_CNS`='gxadmision' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='1' WHERE  `Campo_CNS`='Codigo_ARE' AND `Tabla_CNS`='czareas' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_EGR' AND `Tabla_CNS`='gxegresos' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_EPS' AND `Tabla_CNS`='gxeps' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_HCM' AND `Tabla_CNS`='hcordenesmedica' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ISF' AND `Tabla_CNS`='czinvsolfarmacia' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_NCT' AND `Tabla_CNS`='cznotascontablesenc' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ORD' AND `Tabla_CNS`='gxordenescab' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_RAD' AND `Tabla_CNS`='czradicacionescab' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_TER' AND `Tabla_CNS`='czterceros' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_TUR' AND `Tabla_CNS`='czturnosenc' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='2' WHERE  `Campo_CNS`='Codigo_USR' AND `Tabla_CNS`='itusuarios' AND `Codigo_DCD`=0;
DELETE FROM `itmensajes`;
DELETE FROM `itusuarios` WHERE  `Codigo_USR` NOT IN ('1','0');
DELETE FROM `itusuariosbodegas`;

