ALTER TABLE `itconfig`	CHANGE COLUMN `Version_DCD` `Version_DCD` VARCHAR(12) NULL DEFAULT NULL AFTER `Updatelink_DCD`;
UPDATE `itconfig` SET `Updatelink_DCD`='update.nexus-it.co/version/', `Version_DCD`='17.07.162220' WHERE  `Licencia_DCD`='037632a4c6ab9014691a8b67a70ffdc315443dae' AND `NIT_DCD`='901073245-9 ' AND `Codigo_DCD`=1;
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`, `SQL_RPT`) VALUES ('kventas', 'Reporte General de Ventas', 'select b.Prefijo_EMI, b.Codigo_EMI, b.Fecha_EMI, b.Codigo_CTZ, c.Nombre_TER, d.Nombre_AGE, e.Nombre_PLA, b.Voucher_EMI, a.Edad_CTZ, a.Modalidad_CTZ, a.FechaIni_CTZ, a.FechaFin_CTZ, a.Dias_CTZ, g.Nombre_DST, h.Nombre_DST, a.Dolares_CTZ, a.Pesos_CTZ, a.Descuento_CTZ, a.Total_CTZ,\r\n concat(f.ID_USR, \'[\', f.Nombre_USR, \']\')\r\nfrom klcotizaciones a, klemisiones b, czterceros c, klagencias d, klplanes e, itusuarios f, kldestinos g, kldestinos h\r\nwhere a.Codigo_DCD=b.Codigo_DCD and a.Codigo_CTZ=b.Codigo_CTZ and a.Codigo_TER=c.Codigo_TER and a.Codigo_AGE=d.Codigo_AGE\r\n and a.Codigo_PLA=e.Codigo_PLA and f.Codigo_USR=b.Codigo_USR and g.Codigo_DST=a.Procedencia_CTZ and h.Codigo_DST=a.Codigo_DST\r\n and b.Estado_EMI<>\'A\' and b.Fecha_EMI between \'@FECHA_INI 00:00:00\' and \'@FECHA_FIN 23:59:59\'\r\n ORDER BY 3');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('kventas', 'FECHA_INI', 'Fecha Inicial', '1', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('kventas', 'FECHA_FIN', 'Fecha Final', '1', 'D');
UPDATE `itreportsparam` SET `Orden_RPT`='2' WHERE  `Codigo_RPT`='kventas' AND `Campo_RPT`='FECHA_FIN' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `Orientacion_RPT`='L' WHERE  `Codigo_RPT`='kventas' AND `Codigo_DCD`=0;
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`, `SQL_RPT`, `Orientacion_RPT`) VALUES ('kventaslocal', 'Reporte Local de Ventas', 'select b.Prefijo_EMI, b.Codigo_EMI, b.Fecha_EMI, b.Codigo_CTZ, c.Nombre_TER, d.Nombre_AGE, e.Nombre_PLA, b.Voucher_EMI, a.Edad_CTZ, a.Modalidad_CTZ, a.FechaIni_CTZ, a.FechaFin_CTZ, a.Dias_CTZ, g.Nombre_DST, h.Nombre_DST, a.Dolares_CTZ, a.Pesos_CTZ, a.Descuento_CTZ, a.Total_CTZ,\r\n concat(f.ID_USR, \'[\', f.Nombre_USR, \']\')\r\nfrom klcotizaciones a, klemisiones b, czterceros c, klagencias d, klplanes e, itusuarios f, kldestinos g, kldestinos h\r\nwhere a.Codigo_DCD=b.Codigo_DCD and a.Codigo_CTZ=b.Codigo_CTZ and a.Codigo_TER=c.Codigo_TER and a.Codigo_AGE=d.Codigo_AGE\r\n and a.Codigo_PLA=e.Codigo_PLA and f.Codigo_USR=b.Codigo_USR and g.Codigo_DST=a.Procedencia_CTZ and h.Codigo_DST=a.Codigo_DST\r\n and b.Estado_EMI<>\'A\' and b.Fecha_EMI between \'@FECHA_INI 00:00:00\' and \'@FECHA_FIN 23:59:59\'', 'L');
UPDATE `itreports` SET `SQL_RPT`='select b.Prefijo_EMI, b.Codigo_EMI, b.Fecha_EMI, b.Codigo_CTZ, c.Nombre_TER, d.Nombre_AGE, e.Nombre_PLA, b.Voucher_EMI, a.Edad_CTZ, a.Modalidad_CTZ, a.FechaIni_CTZ, a.FechaFin_CTZ, a.Dias_CTZ, g.Nombre_DST, h.Nombre_DST, a.Dolares_CTZ, a.Pesos_CTZ, a.Descuento_CTZ, a.Total_CTZ,\r\n concat(f.ID_USR, \'[\', f.Nombre_USR, \']\')\r\nfrom klcotizaciones a, klemisiones b, czterceros c, klagencias d, klplanes e, itusuarios f, kldestinos g, kldestinos h, klagenciasusuarios i\r\nwhere a.Codigo_DCD=b.Codigo_DCD and a.Codigo_CTZ=b.Codigo_CTZ and a.Codigo_TER=c.Codigo_TER and a.Codigo_AGE=d.Codigo_AGE\r\n and a.Codigo_PLA=e.Codigo_PLA and f.Codigo_USR=b.Codigo_USR and g.Codigo_DST=a.Procedencia_CTZ and h.Codigo_DST=a.Codigo_DST\r\n and b.Estado_EMI<>\'A\' and b.Fecha_EMI between \'@FECHA_INI 00:00:00\' and \'@FECHA_FIN 23:59:59\' and i.Codigo_AGE=d.Codigo_AGE and i.Codigo_USR=\'@USUARIO\'' WHERE  `Codigo_RPT`='kventaslocal' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='select b.Prefijo_EMI,  LPAD(b.Codigo_EMI,10,\'0\'), b.Fecha_EMI, b.Codigo_CTZ, c.Nombre_TER, d.Nombre_AGE, e.Nombre_PLA, b.Voucher_EMI, a.Edad_CTZ, a.Modalidad_CTZ, a.FechaIni_CTZ, a.FechaFin_CTZ, a.Dias_CTZ, g.Nombre_DST, h.Nombre_DST, a.Dolares_CTZ, a.Pesos_CTZ, a.Descuento_CTZ, a.Total_CTZ,\r\n concat(f.ID_USR, \'[\', f.Nombre_USR, \']\')\r\nfrom klcotizaciones a, klemisiones b, czterceros c, klagencias d, klplanes e, itusuarios f, kldestinos g, kldestinos h\r\nwhere a.Codigo_DCD=b.Codigo_DCD and a.Codigo_CTZ=b.Codigo_CTZ and a.Codigo_TER=c.Codigo_TER and a.Codigo_AGE=d.Codigo_AGE\r\n and a.Codigo_PLA=e.Codigo_PLA and f.Codigo_USR=b.Codigo_USR and g.Codigo_DST=a.Procedencia_CTZ and h.Codigo_DST=a.Codigo_DST\r\n and b.Estado_EMI<>\'A\' and b.Fecha_EMI between \'@FECHA_INI 00:00:00\' and \'@FECHA_FIN 23:59:59\'\r\n ORDER BY 3' WHERE  `Codigo_RPT`='kventas' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='select b.Prefijo_EMI,   LPAD(b.Codigo_EMI,10,\'0\'), b.Fecha_EMI, b.Codigo_CTZ, c.Nombre_TER, d.Nombre_AGE, e.Nombre_PLA, b.Voucher_EMI, a.Edad_CTZ, a.Modalidad_CTZ, a.FechaIni_CTZ, a.FechaFin_CTZ, a.Dias_CTZ, g.Nombre_DST, h.Nombre_DST, a.Dolares_CTZ, a.Pesos_CTZ, a.Descuento_CTZ, a.Total_CTZ,\r\n concat(f.ID_USR, \'[\', f.Nombre_USR, \']\')\r\nfrom klcotizaciones a, klemisiones b, czterceros c, klagencias d, klplanes e, itusuarios f, kldestinos g, kldestinos h, klagenciasusuarios i\r\nwhere a.Codigo_DCD=b.Codigo_DCD and a.Codigo_CTZ=b.Codigo_CTZ and a.Codigo_TER=c.Codigo_TER and a.Codigo_AGE=d.Codigo_AGE\r\n and a.Codigo_PLA=e.Codigo_PLA and f.Codigo_USR=b.Codigo_USR and g.Codigo_DST=a.Procedencia_CTZ and h.Codigo_DST=a.Codigo_DST\r\n and b.Estado_EMI<>\'A\' and b.Fecha_EMI between \'@FECHA_INI 00:00:00\' and \'@FECHA_FIN 23:59:59\' and i.Codigo_AGE=d.Codigo_AGE and i.Codigo_USR=\'@USUARIO\'\r\nOrder by 6, 3' WHERE  `Codigo_RPT`='kventaslocal' AND `Codigo_DCD`=0;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('kventaslocal', 'FECHA_INI', 'Fecha Inicial', '1', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('kventaslocal', 'FECHA_FIN', 'Fecha Final', '2', 'D');
UPDATE `itreports` SET `SQL_RPT`='Select i.Razonsocial_DCD, i.NIT_DCD, h.Codigo_EMI, date(h.Fecha_EMI), h.Codigo_USR, ID_TER as \'Pasaporte\', Nombre_TER as \'Nombres\', FechaNac_KLI as \'Fecha Nacimiento\', Nombre_AGE as \'Agencia\', Nombre_USR as \'Promotor\', nombre_pla as \'Plan\', Modalidad_CTZ as \'Modalidad\', f.nombre_dst as \'Procedencia\', g.nombre_dst as \'Destino\', FechaIni_CTZ as \'Fecha Inicio\', FechaFin_CTZ as \'Fecha Fin\', Dias_CTZ as \'Días\', TRM_CTZ as \'T.R.M.\', Dolares_CTZ as \'Valor en Dolares\', Pesos_CTZ as \'Valor en Pesos\', Voucher_CTZ as \'Voucher\',a.Direccion_TER, a.Telefono_TER, k.Descripcion_EST as \'Estado\', h.Prefijo_EMI as \'Prefijo\'  \r\nFrom czterceros a, klcotizaciones b, itusuarios c, klagencias d, klplanes e, kldestinos f, kldestinos g, klemisiones h, itconfig i, klclientes j, klestadosventas k  \r\nWhere a.codigo_ter=b.codigo_ter and c.codigo_usr=b.codigo_usr and d.codigo_age=b.codigo_age and e.codigo_pla=b.codigo_pla and j.Codigo_TER=b.Codigo_TER and  \r\nf.codigo_dst=procedencia_ctz and g.codigo_dst=b.codigo_dst and k.Codigo_EST=h.Estado_EMI and\r\nb.codigo_ctz=h.Codigo_CTZ  and LPAD(h.Codigo_EMI,10,\'0\')>=LPAD(\'@EMISION_INICIAL\',10,\'0\') and LPAD(h.Codigo_EMI,10,\'0\')<=LPAD(\'@EMISION_FINAL\',10,\'0\')  and h.Prefijo_EMI<=\'@PREFIJO\' ' WHERE  `Codigo_RPT`='klemisiones' AND `Codigo_DCD`=0;
INSERT INTO `klestadosventas` (`Codigo_EST`, `Descripcion_EST`) VALUES ('A', 'Anulado');
CREATE TABLE `gxagenda` (	`Codigo_TER` VARCHAR(10) NOT NULL,	`Codigo_ARE` VARCHAR(3) NULL,	`Codigo_CNS` VARCHAR(6) NULL,	`Fecha_AGE` DATE NOT NULL,	`Hora_AGE` VARCHAR(5) NOT NULL,	`Tiempo_AGE` DECIMAL(2) NULL,	`FechaGraba_AGE` DATETIME NULL,	`Codigo_USR` VARCHAR(4) NULL,	`Estado_AGE` CHAR(1) NOT NULL DEFAULT '1',	PRIMARY KEY (`Codigo_TER`, `Fecha_AGE`, `Hora_AGE`, `Estado_AGE`), INDEX `Codigo_ARE` (`Codigo_ARE`),	INDEX `Codigo_CNS` (`Codigo_CNS`),	INDEX `Fecha_AGE` (`Fecha_AGE`),	INDEX `Codigo_TER` (`Codigo_TER`),	INDEX `Estado_AGE` (`Estado_AGE`)) COMMENT='Agenda Consulta Externa' COLLATE='utf8_unicode_ci' ENGINE=InnoDB;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`) VALUES ('424', '100', '18', '2', 'Agenda Medica', '1.UserSetup.png', 'forms/agenda.php');
UPDATE `ititems` SET `Icono_ITM`='1.LastThreeMonths.png' WHERE  `Codigo_ITM`=424 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
ALTER TABLE `gxagenda`	ADD COLUMN `Codigo_ESP` VARCHAR(10) NOT NULL AFTER `Codigo_TER`,	ADD INDEX `Codigo_ESP` (`Codigo_ESP`);
ALTER TABLE `cznotascontablesenc` 	CHANGE COLUMN `Codigo_CCT` `Codigo_CCT` VARCHAR(3) NULL DEFAULT '1' COMMENT 'Centro de Costo' AFTER `Codigo_CNT`;
UPDATE `itconfig` SET `Version_DCD`='17.08.24.001';
ALTER TABLE `gxareas`	ADD COLUMN `Habitacion_ARE` ENUM('1','0') NULL DEFAULT '0' AFTER `Nombre_ARE`,	ADD COLUMN `Urgencias_ARE` ENUM('1','0') NULL DEFAULT '0' AFTER `Habitacion_ARE`,	ADD COLUMN `Historia_ARE` ENUM('1','0') NULL DEFAULT '1' AFTER `Urgencias_ARE`,	ADD COLUMN `Salida_ARE` ENUM('1','0') NULL DEFAULT '1' AFTER `Historia_ARE`,	ADD COLUMN `Cirugia_ARE` ENUM('1','0') NULL DEFAULT '0' AFTER `Salida_ARE`,	ADD COLUMN `Traslados_ARE` ENUM('1','0') NULL DEFAULT '1' AFTER `Cirugia_ARE`,	ADD COLUMN `AgendaCitas_ARE` ENUM('1','0') NULL DEFAULT '0' AFTER `Traslados_ARE`,	ADD INDEX `Habitacion_ARE` (`Habitacion_ARE`),	ADD INDEX `Urgencias_ARE` (`Urgencias_ARE`),	ADD INDEX `Historia_ARE` (`Historia_ARE`),	ADD INDEX `Salida_ARE` (`Salida_ARE`),	ADD INDEX `Cirugia_ARE` (`Cirugia_ARE`),	ADD INDEX `Traslados_ARE` (`Traslados_ARE`),	ADD INDEX `AgendaCitas_ARE` (`AgendaCitas_ARE`),	ADD INDEX `Estado_ARE` (`Estado_ARE`);
ALTER TABLE `gxareas`	ADD COLUMN `HoraIni_ARE` TIME NULL DEFAULT '00:00' AFTER `AgendaCitas_ARE`,	ADD COLUMN `HoraFin_ARE` TIME NULL DEFAULT '00:00' AFTER `HoraIni_ARE`;
CREATE TABLE `gxconsultorios` (	`Codigo_DCD` INT(5) NOT NULL,	`Codigo_CNS` VARCHAR(6) NOT NULL,	`Nombre_CNS` VARCHAR(15) NULL,	`Descripcion_CNS` VARCHAR(50) NULL,	`Codigo_ARE` VARCHAR(4) NULL,	`Estado_CNS` ENUM('1','0') NULL DEFAULT '1',	PRIMARY KEY (`Codigo_DCD`, `Codigo_CNS`),	UNIQUE INDEX `Codigo_DCD_Codigo_CNS` (`Codigo_DCD`, `Codigo_CNS`),	INDEX `Estado_CNS` (`Estado_CNS`),	INDEX `Codigo_ARE` (`Codigo_ARE`),	INDEX `Codigo_CNS` (`Codigo_CNS`),	INDEX `Codigo_DCD` (`Codigo_DCD`),	INDEX `Codigo_ARE_Estado_CNS` (`Codigo_ARE`, `Estado_CNS`)) COMMENT='Consultorios' COLLATE='utf8_general_ci' ENGINE=InnoDB;
INSERT INTO `itconsecutivos` (`Codigo_CNS`, `Tabla_CNS`, `Campo_CNS`, `Consecutivo_CNS`, `Descripcion_CNS`) VALUES ('32', 'gxconsultorios', 'Codigo_CNS', '1', 'Consultorios Medicos');
ALTER TABLE `gxareas`	ADD COLUMN `TiempoConsulta_ARE` INT NULL DEFAULT '15' AFTER `HoraFin_ARE`;
Update ititems Set OptNo_ITM='1', OptPrinter_ITM='1', OpSave_ITM='1', OptNew_ITM='1' ;
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0'  Where enlace_itm='forms/pacientes.php'; 
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/ingresos.php'; 
Update ititems Set OptNew_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0' Where enlace_itm='forms/ingresosno.php';			
Update ititems Set OptNew_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0' Where enlace_itm='forms/ordenesdeserviciono.php'; 
Update ititems Set OptPrinter_ITM='0', OptNo_ITM='0' Where enlace_itm='forms/ordenesdeservicio.php'; 
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/contratos.php'; 
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/mantarifas.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/planeseps.php';			
Update ititems Set OptNew_ITM='0', OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/cubrimientocontrato.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/egresos.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/servicios.php';			
Update ititems Set OptPrinter_ITM='0', OptNo_ITM='0' Where enlace_itm='forms/facturasalud.php';			
Update ititems Set OptNew_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0' Where enlace_itm='forms/facturasaludno.php';		
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/radicaciones.php';			
Update ititems Set OptNew_ITM='0', OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/radicacionesconf.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0' Where enlace_itm='forms/rips.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/perfilesusuarios.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/empleados.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/myempleados.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/idnexusconf.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/cargosemp.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/festivos.php';			
Update ititems Set OptNo_ITM='0' Where enlace_itm='forms/turnosconf.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/areascz.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/myturnos.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/cambiarturnos.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/sqlbuddy.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/usuarios.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/salariosemp.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/cargos.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/marcacionesid.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OpSave_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/collate.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/turnosmes.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/areasemp.php'; 
Update ititems Set OptNo_ITM='0', OpSave_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/myprodu.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/solicitudods.php';			
Update ititems Set OptNo_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/respuestaods.php';			
Update ititems Set OptPrinter_ITM='0', OptNo_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/interfazsiigo.php';			
Update ititems Set OptPrinter_ITM='0', OptNo_ITM='0' Where enlace_itm='forms/proveedores.php';			
Update ititems Set OptPrinter_ITM='0', OptNo_ITM='0' Where enlace_itm='forms/referencias.php'; 
Update ititems Set OptPrinter_ITM='0', OptNo_ITM='0' Where enlace_itm='forms/bodegas.php';			
Update ititems Set OptNo_ITM='0' Where enlace_itm='forms/inventarioentra.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0', OptNew_ITM='0' Where enlace_itm='forms/autorizaciones.php';		
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/facturasaludlote.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/medicos.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/especialidades.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/medicos.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/hcmodelos.php'; 
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/hc.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/hcenfermeria.php';			
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/hcnotas.php';
Update ititems Set OptNo_ITM='0', OptNew_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/inventariodesp.php';			
Update ititems Set OptNo_ITM='0', OpSave_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/hcrevision.php';
Update ititems Set OptNo_ITM='0', OptPrinter_ITM='0' Where enlace_itm='forms/notascredito.php';
UPDATE `ititems` SET `OptPrinter_ITM`='0', `OptNew_ITM`='0', `OptNo_ITM`='0' WHERE  `Codigo_ITM`=424 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `itreports` SET `SQL_RPT`='select a.Codigo_ADM, f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, \r\ndate(a.Fecha_ADM), g.Codigo_DGN, sum(i.Cantidad_ORD * l.Valor_TAR),  n.Nombre_SDE, a.estado_adm, a.Autorizacion_ADM \r\nFrom gxadmision a, gxpacientes b, czterceros c,  cztipoid f, gxdiagnostico g, gxordenescab h, gxordenesdet i, gxservicios j, itusuariossedes k, gxmanualestarifarios l, gxcontratos m, czsedes n \r\nWhere a.Codigo_TER=b.Codigo_TER and b.Codigo_TER=c.Codigo_TER and h.Codigo_ORD=i.Codigo_ORD and h.Codigo_ADM=a.Codigo_ADM and k.Codigo_USR=a.Codigo_USR and n.Codigo_SDE=k.Codigo_SDE\r\nand j.Codigo_SER=i.Codigo_SER and f.Codigo_TID=c.Codigo_TID and g.Codigo_DGN=a.Codigo_DGN and l.Codigo_DCD=a.Codigo_DCD and l.Codigo_TAR=m.Codigo_TAR and m.Codigo_DCD=a.Codigo_DCD and m.Codigo_EPS=a.Codigo_EPS and m.Codigo_PLA=a.Codigo_PLA and l.Codigo_SER=i.Codigo_SER and h.Fecha_ORD <= l.FechaFin_TAR and h.Fecha_ORD >= l.FechaIni_TAR \r\nand a.Fecha_ADM>=\'@FECHA_INICIAL\' and a.Fecha_ADM<=\'@FECHA_FINAL\' and a.Codigo_EPS=\'@ENTIDAD\'\r\nand a.estado_adm<>\'A\' \r\nGroup by f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, date(a.Fecha_ADM), g.Descripcion_DGN,  k.Codigo_SDE, a.estado_adm\r\nOrder by 11, 4, 5, 6' WHERE  `Codigo_RPT`='servicioscargadosfecha' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='select a.Codigo_ADM, f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, \r\ndate(a.Fecha_ADM), g.Codigo_DGN, sum(i.Cantidad_ORD * l.Valor_TAR),  n.Nombre_SDE, a.estado_adm, a.Autorizacion_ADM \r\nFrom gxadmision a, gxpacientes b, czterceros c,  cztipoid f, gxdiagnostico g, gxordenescab h, gxordenesdet i, gxservicios j, itusuariossedes k, gxmanualestarifarios l, gxcontratos m, czsedes n \r\nWhere a.Codigo_TER=b.Codigo_TER and b.Codigo_TER=c.Codigo_TER and h.Codigo_ORD=i.Codigo_ORD and h.Codigo_ADM=a.Codigo_ADM and k.Codigo_USR=a.Codigo_USR and n.Codigo_SDE=k.Codigo_SDE\r\nand j.Codigo_SER=i.Codigo_SER and f.Codigo_TID=c.Codigo_TID and g.Codigo_DGN=a.Codigo_DGN and l.Codigo_DCD=a.Codigo_DCD and l.Codigo_TAR=m.Codigo_TAR and m.Codigo_DCD=a.Codigo_DCD and m.Codigo_EPS=a.Codigo_EPS and m.Codigo_PLA=a.Codigo_PLA and l.Codigo_SER=i.Codigo_SER and h.Fecha_ORD <= l.FechaFin_TAR and h.Fecha_ORD >= l.FechaIni_TAR \r\nand a.Fecha_ADM>=\'@FECHA_INICIAL 00:00:00\' and a.Fecha_ADM<=\'@FECHA_FINAL 23:59:59\' and a.Codigo_EPS=\'@ENTIDAD\' \r\nand a.estado_adm<>\'A\' \r\nGroup by f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, date(a.Fecha_ADM), g.Descripcion_DGN,  k.Codigo_SDE, a.estado_adm\r\nOrder by 11, 4, 5, 6' WHERE  `Codigo_RPT`='servicioscargadosfecha' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='select a.Codigo_ADM, f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, \r\ndate(a.Fecha_ADM), g.Codigo_DGN, sum(i.Cantidad_ORD * l.Valor_TAR),  n.Nombre_SDE, a.estado_adm, a.Autorizacion_ADM \r\nFrom gxadmision a, gxpacientes b, czterceros c,  cztipoid f, gxdiagnostico g, gxordenescab h, gxordenesdet i, gxservicios j, itusuariossedes k, gxmanualestarifarios l, gxcontratos m, czsedes n \r\nWhere a.Codigo_TER=b.Codigo_TER and b.Codigo_TER=c.Codigo_TER and h.Codigo_ORD=i.Codigo_ORD and h.Codigo_ADM=a.Codigo_ADM and k.Codigo_USR=a.Codigo_USR and n.Codigo_SDE=k.Codigo_SDE  and n.Codigo_SDE=a.Codigo_SDE \r\nand j.Codigo_SER=i.Codigo_SER and f.Codigo_TID=c.Codigo_TID and g.Codigo_DGN=a.Codigo_DGN and l.Codigo_DCD=a.Codigo_DCD and l.Codigo_TAR=m.Codigo_TAR and m.Codigo_DCD=a.Codigo_DCD and m.Codigo_EPS=a.Codigo_EPS and m.Codigo_PLA=a.Codigo_PLA and l.Codigo_SER=i.Codigo_SER and h.Fecha_ORD <= l.FechaFin_TAR and h.Fecha_ORD >= l.FechaIni_TAR \r\nand a.Fecha_ADM>=\'@FECHA_INICIAL 00:00:00\' and a.Fecha_ADM<=\'@FECHA_FINAL 23:59:59\' and a.Codigo_EPS=\'@ENTIDAD\' \r\nand a.estado_adm<>\'A\' \r\nGroup by f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, date(a.Fecha_ADM), g.Descripcion_DGN,  k.Codigo_SDE, a.estado_adm\r\nOrder by 11, 4, 5, 6' WHERE  `Codigo_RPT`='servicioscargadosfecha' AND `Codigo_DCD`=0;
ALTER TABLE `ititems`	ADD INDEX `Enlace_ITM` (`Enlace_ITM`);





INSERT INTO `hctipos` (`Codigo_HCT`, `Nombre_HCT`, `Codigo_HCH`, `Epicrisis_HCT`, `SV_HCT`, `Antecedentes_HCT`, `AyudasDiag_HCT`, `Med_HCT`, `Ordenes_HCT`, `Indicaciones_HCT`) VALUES ('ODONTO1', 'HISTORIA CLINICA DE ODONTOLOGIA', '2', '1', '1', '1', '1', '1', '1', '1');
INSERT INTO `hctipos` (`Codigo_HCT`, `Nombre_HCT`, `Codigo_HCH`, `Epicrisis_HCT`, `SV_HCT`, `Dx_HCT`, `AyudasDiag_HCT`, `Med_HCT`, `Ordenes_HCT`, `Indicaciones_HCT`, `Img_HCT`) VALUES ('ODONTO2', 'CONSULTA DE CONTROL ODONTOLOGIA', '2', '1', '1', '1', '1', '1', '1', '1', '1');

INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('425', '92', '6', '2', 'Listado Pacientes Consulta', 'forms/ptescext.php', '0');
UPDATE `ititems` SET `Icono_ITM`='1.History.png' WHERE  `Codigo_ITM`=425 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
ALTER TABLE `gxeps`	ADD INDEX `Contrato_EPS` (`Contrato_EPS`);
CREATE TABLE `gxpacientescapita` (	`Codigo_TER` VARCHAR(10) NOT NULL,	`Contrato_EPS` VARCHAR(50) NOT NULL,	PRIMARY KEY (`Codigo_TER`, `Contrato_EPS`),	INDEX `Codigo_TER` (`Codigo_TER`),	INDEX `Contrato_EPS` (`Contrato_EPS`)) COMMENT='Poblacion Capitada por Contrato' COLLATE='utf8_general_ci' ENGINE=InnoDB;

INSERT INTO `gxpacientestipos` (`Codigo_PTT`) VALUES ('3');
UPDATE `gxpacientestipos` SET `Nombre_PTT`='Alta temprana', `Reingreso_PTT`='0' WHERE  `Codigo_PTT`='3' AND `Codigo_DCD`=0;
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`) VALUES ('hcformulamedica', 'Formula Medica');
UPDATE `itreports` SET `SQL_RPT`='Select c.CUM_MED, c.Nombre_MED, Dosis_HCM, Descripcion_VIA, Descripcion_FRC, Duracion_HCM, Estado_HCM, Observaciones_HCM, Cantidad_HCM From hcordenesmedica a, czterceros b, gxmedicamentos c, gxviasmed d, gxfrecuenciamed e where e.Codigo_FRC=Frecuencia_HCM and d.Codigo_VIA=Via_HCM and a.Codigo_TER=b.Codigo_TER and c.Codigo_SER=a.Codigo_SER and a.Codigo_HCF=\'@FOLIO\' and b.ID_TER=\'@HISTORIA\' order by 2' WHERE  `Codigo_RPT`='hcformulamedica' AND `Codigo_DCD`=0;

UPDATE `ititems` SET `Enlace_ITM`='forms/hclistaformedica.php' WHERE  `Codigo_ITM`=381 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Icono_ITM`='1.Pills.png' WHERE  `Codigo_ITM`=381 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `OptPrinter_ITM`='0', `OptNo_ITM`='0', `OpSave_ITM`='0' WHERE  `Codigo_ITM`=381 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `itreports` SET `SQL_RPT`='select a.Razonsocial_DCD, a.NIT_DCD, a.Direccion_DCD, a.Telefonos_DCD, e.Logo2_HCH, b.Nombre_HCT\r\nFrom\r\n itconfig a, hctipos b, hcfolios c, czterceros d, hcencabezadosdet e, hcordenesmedica f\r\nWhere \r\n f.Codigo_TER=c.Codigo_TER and f.Codigo_HCF=c.Codigo_HCF and c.Codigo_TER=d.Codigo_TER and c.Codigo_HCT=b.Codigo_HCT and b.Codigo_HCH=e.Codigo_HCH\r\n and d.ID_TER=\'@HISTORIA\' and c.Codigo_HCF>=\'@FOLIO_INICIAL\' and c.Codigo_HCF<=\'@FOLIO_FINAL\'' WHERE  `Codigo_RPT`='hcformulamedica' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `Page_RPT`='halfletter' WHERE  `Codigo_RPT`='hcformulamedica' AND `Codigo_DCD`=0;
UPDATE `hccampos` SET `Normalizar_HCC`='1' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='examfisico';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='cabycue';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='torax';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='abdomen';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='extrem';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='piel';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='genital';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='orgsentidos';
UPDATE `hccampos` SET `Defecto_HCC`='SIN ALTERACION APARENTE' WHERE  `Codigo_HCT`='HC01' AND `Codigo_HCC`='neurolog';
UPDATE `hcsv2` SET `Calculo_HSV`='04/(05*05)' WHERE  `Codigo_HSV`='07';
UPDATE `hcsv2` SET `Calculo_HSV`='08*{1000}/(09*09*{10000})' WHERE  `Codigo_HSV`='10';
UPDATE `hcsv2` SET `Vinculado_HSV`='07' WHERE  `Codigo_HSV`='04';
UPDATE `hcsv2` SET `Vinculado_HSV`='07' WHERE  `Codigo_HSV`='05';
UPDATE `hcsv2` SET `Vinculado_HSV`='10' WHERE  `Codigo_HSV`='08';
UPDATE `hcsv2` SET `Vinculado_HSV`='10' WHERE  `Codigo_HSV`='09';
UPDATE `hcsv2` SET `Vinculado_HSV`='' WHERE  `Codigo_HSV`='01';
UPDATE `hcsv2` SET `Vinculado_HSV`='' WHERE  `Codigo_HSV`='02';
UPDATE `hcsv2` SET `Vinculado_HSV`='' WHERE  `Codigo_HSV`='03';
UPDATE `hcsv2` SET `Vinculado_HSV`='' WHERE  `Codigo_HSV`='06';
UPDATE `hcsv2` SET `Vinculado_HSV`='' WHERE  `Codigo_HSV`='07';
UPDATE `hcsv2` SET `Vinculado_HSV`='' WHERE  `Codigo_HSV`='10';
UPDATE `hcsv2` SET `Calculo_HSV`='{04}/({05}*{05})' WHERE  `Codigo_HSV`='07';
UPDATE `hcsv2` SET `Calculo_HSV`='{08}*1000/({09}*{09}*10000)' WHERE  `Codigo_HSV`='10';

