UPDATE `itconfig` SET `Version_DCD`='17.11.03.001';
UPDATE `hctipos` SET `Epicrisis_HCT`='1', `SV_HCT`='3', `Indicaciones_HCT`='1' WHERE  `Codigo_HCT`='TREVTRQ';
ALTER TABLE `itconfig_hc` ADD COLUMN `OrdHlpDx_XHC` CHAR(1) NULL DEFAULT '0' COMMENT 'Generar Solicitud de Imagenes Dx o Laboratorios' AFTER `AplMedFac_XHC`,	ADD COLUMN `OrdHDxFac_XHC` CHAR(1) NULL DEFAULT '0' COMMENT 'Realizar Orden Servicio Facturacion desde solicitud de paraclinicos' AFTER `OrdHlpDx_XHC`,	ADD INDEX `OrdHlpDx_XHC` (`OrdHlpDx_XHC`),	ADD INDEX `OrdHDxFac_XHC` (`OrdHDxFac_XHC`);
ALTER TABLE `itconfig_hc`	ADD COLUMN `OrdCuraFac_XHC` CHAR(1) NULL DEFAULT '1' COMMENT 'Generar cobro de curaciones segun el tipo' AFTER `AplMedFac_XHC`,	ADD INDEX `OrdCuraFac_XHC` (`OrdCuraFac_XHC`);
ALTER TABLE `itconfig_hc`	ADD COLUMN `OrdDispFac_XHC` CHAR(1) NULL DEFAULT '1' COMMENT 'Realizar Orden de servicio de cambio dispositivos' AFTER `OrdCuraFac_XHC`,	ADD INDEX `OrdDispFac_XHC` (`OrdDispFac_XHC`);
ALTER TABLE `gxmedicamentos`	CHANGE COLUMN `Concentracion_MED` `Concentracion_MED` DECIMAL(10,2) NULL DEFAULT '0' AFTER `Dispositivo_MED`;
UPDATE `ititems` SET `OptPrinter_ITM`='0', `OptNo_ITM`='0' WHERE  `Codigo_ITM`=375 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `itreports` SET `SQL_RPT`='SELECT c.Codigo_SER, c.Nombre_SER, sum(a.Cantidad_ORD), b.Nombre_TER, g.Nombre_SDE, e.Codigo_ADM, h.Nombre_TER\r\nFROM gxordenesdet a, czterceros b, gxservicios c, gxordenescab d, gxadmision e, czsedes g, czterceros h    \r\nWHERE  a.Codigo_TER= b.Codigo_TER AND a.Codigo_SER= c.Codigo_SER AND d.Codigo_ORD=a.Codigo_ORD AND h.Codigo_TER=e.Codigo_TER \r\nAND e.Codigo_ADM=d.Codigo_ADM AND g.Codigo_SDE=e.Codigo_SDE AND e.Estado_ADM<>\'A\' AND d.Estado_ORD<>\'0\' \r\nAND b.ID_TER >= \'@PROFESIONAL1\' AND b.ID_TER <=\'@PROFESIONAL2\' AND d.Fecha_ORD >=\'@FECHA_INICIAL\' AND d.Fecha_ORD <=\'@FECHA_FINAL\' \r\nGroup By g.Nombre_SDE, b.Nombre_TER, c.Codigo_SER, c.Nombre_SER, e.Codigo_ADM, h.Nombre_TER\r\nOrder By g.Nombre_SDE, b.Nombre_TER, h.Nombre_TER, c.Codigo_SER, c.Nombre_SER' WHERE  `Codigo_RPT`='servprofesional' AND `Codigo_DCD`=0;

