UPDATE `itconfig` SET `Version_DCD`='18.12.03.001';
UPDATE `ititems` SET `Icono_ITM`='document_num.png' WHERE  `Codigo_ITM`=473 AND `Codigo_MNU`=50 AND `Codigo_MOD`=3 AND `Codigo_APP`=2;
ALTER TABLE `czautfacturacion`	ADD COLUMN `FechaIni_AFC` DATE NULL DEFAULT '2018-01-01' AFTER `ConsecNow_AFC`,	ADD COLUMN `FechaFin_AFC` DATE NULL DEFAULT '2500-12-31' AFTER `FechaIni_AFC`;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`) VALUES ('474', '100', '18', '2', 'Sedes', '1.LastThreeMonths.png', 'forms/sedes.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`) VALUES ('475', '100', '18', '2', 'Consultorios', '1.LastThreeMonths.png', 'forms/consultorios.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`) VALUES ('476', '100', '18', '2', 'Dias Feriados', '1.LastThreeMonths.png', 'forms/festivos.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('477', '100', '18', '2', 'Parámetros', 'forms/configagendamedica.php');
INSERT INTO `hcsv1` (`Codigo_SV1`, `Nombre_SV1`) VALUES ('4', 'Signos Vitales CardioVascular');
ALTER TABLE `hcsv2`	CHANGE COLUMN `Sigla_HSV` `Sigla_HSV` CHAR(15) NULL DEFAULT NULL AFTER `Nombre_HSV`;
INSERT INTO `hcsv2` (`Codigo_HSV`, `Nombre_HSV`, `Sigla_HSV`, `Min_HSV`, `Max_HSV`, `Vinculado_HSV`) VALUES ('11', 'Tensión Arterial (De Pie)', 'TA (De Pie)', '0', '200', '');
INSERT INTO `hcsv2` (`Codigo_HSV`, `Nombre_HSV`, `Sigla_HSV`, `Min_HSV`, `Max_HSV`, `Vinculado_HSV`) VALUES ('12', 'Tensión Arterial (Acostado)', 'TA (Acostado)', '0', '200', '');
INSERT INTO `hcsv2` (`Codigo_HSV`, `Nombre_HSV`, `Sigla_HSV`, `Min_HSV`, `Max_HSV`, `Vinculado_HSV`) VALUES ('13', 'Tensión Arterial (Sentado)', 'TA (Sentado)', '0', '200', '');
Insert into hcsv3 Select a.Codigo_HSV, '4', a.Orden_HSV +4 from hcsv3 a where a.Codigo_SV1='1';
INSERT INTO `gnx_ircips`.`hcsv3` (`Codigo_HSV`, `Codigo_SV1`, `Orden_HSV`) VALUES ('11', '4', '1');
INSERT INTO `gnx_ircips`.`hcsv3` (`Codigo_HSV`, `Codigo_SV1`, `Orden_HSV`) VALUES ('12', '4', '2');
INSERT INTO `gnx_ircips`.`hcsv3` (`Codigo_HSV`, `Codigo_SV1`, `Orden_HSV`) VALUES ('13', '4', '3');
UPDATE `hctipos` SET `SV_HCT`='4' WHERE  `Codigo_HCT`='HCHTA1';
DELETE FROM `hcsv3` WHERE  `Codigo_HSV`='01' AND `Codigo_SV1`='4';
UPDATE `hcsv3` SET `Orden_HSV`='5' WHERE  `Codigo_HSV`='02' AND `Codigo_SV1`='4';
UPDATE `hcsv3` SET `Orden_HSV`='6' WHERE  `Codigo_HSV`='03' AND `Codigo_SV1`='4';
UPDATE `hcsv3` SET `Orden_HSV`='7' WHERE  `Codigo_HSV`='04' AND `Codigo_SV1`='4';
UPDATE `hcsv3` SET `Orden_HSV`='8' WHERE  `Codigo_HSV`='05' AND `Codigo_SV1`='4';
UPDATE `hcsv3` SET `Orden_HSV`='9' WHERE  `Codigo_HSV`='06' AND `Codigo_SV1`='4';
UPDATE `hcsv3` SET `Orden_HSV`='10' WHERE  `Codigo_HSV`='07' AND `Codigo_SV1`='4';
CREATE TABLE `hcincapacidades` (	`Codigo_TER` CHAR(10) NULL,	`Codigo_HCF` INT NULL) COMMENT='Incapacidades Médicas' COLLATE='utf8_general_ci' ENGINE=InnoDB;
ALTER TABLE `hcincapacidades`	ADD COLUMN `Fecha_HCI` DATETIME NULL DEFAULT NULL AFTER `Codigo_HCF`,	ADD COLUMN `FechaIni_HCI` DATE NULL DEFAULT NULL AFTER `Fecha_HCI`;
ALTER TABLE `hcincapacidades`	ADD COLUMN `Codigo_HCI` INT NULL DEFAULT NULL AFTER `Fecha_HCI`,	ADD COLUMN `Dias_HCI` INT NULL DEFAULT NULL AFTER `FechaIni_HCI`,	ADD COLUMN `FechaFin_HCI` DATE NULL DEFAULT NULL AFTER `Dias_HCI`;
ALTER TABLE `hcincapacidades`	CHANGE COLUMN `Codigo_TER` `Codigo_TER` CHAR(10) NOT NULL FIRST,	CHANGE COLUMN `Codigo_HCF` `Codigo_HCF` INT(11) NOT NULL AFTER `Codigo_TER`,	CHANGE COLUMN `Fecha_HCI` `Fecha_INC` DATETIME NOT NULL AFTER `Codigo_HCF`,	ADD COLUMN `Codigo_HMI` INT NULL DEFAULT NULL AFTER `FechaFin_HCI`,	ADD COLUMN `Codigo_HTI` INT NULL DEFAULT NULL AFTER `Codigo_HMI`,	ADD COLUMN `Observaciones_INC` VARCHAR(255) NULL DEFAULT NULL AFTER `Codigo_HTI`,	ADD PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`, `Fecha_INC`),	ADD INDEX `Codigo_TER` (`Codigo_TER`),	ADD INDEX `Codigo_HCF` (`Codigo_HCF`),	ADD INDEX `FechaIni_HCI` (`FechaIni_HCI`);