delete from czcartera;
delete from czradicacionesdet;
delete from czradicacionescab;
delete from czturnosdet;
delete from czturnosenc;
delete from gxordenesdet;
delete from gxordenescab;
delete from gxmedicosesp;
delete from gxadmision;
delete from gxegresos;
delete from gxfacturas;
delete from czempleados;
DELETE FROM czareasterceros;
DELETE FROM gxpacientes where codigo_ter <>'0';

delete from czterceros where codigo_ter not in ('0', '1');
delete from itusuarios where codigo_usr not in ('0','1');
DELETE FROM czareas;
DELETE FROM czautfacturacion;
DELETE FROM czcentrocosto WHERE  `Codigo_CCT`<>'1' AND `Codigo_DCD`=0;
DELETE FROM czinvsalidasdet;
DELETE FROM czinvsalidascab;
DELETE FROM czinvsolfarmacia;
DELETE FROM cznotascontablesdet;
DELETE FROM cznotascontablesenc;
DELETE FROM czproveedores;

DELETE FROM czsedes;
DELETE FROM gxcontratos;
DELETE FROM gxeps WHERE  `Codigo_EPS`<>'0' AND `Codigo_DCD`=0;
DELETE FROM gxmedicos;

INSERT INTO czareas (`Nombre_ARE`, `Codigo_CCT`, `Codigo_TER`) VALUES ('Consulta Externa', '0', '1');
INSERT INTO czsedes (`Codigo_SDE`, `Nombre_SDE`, `Codigo_AFC`) VALUES ('0', 'Sede Principal', '1');

UPDATE `itconsecutivos` SET `Consecutivo_CNS`='1' WHERE  `Campo_CNS`='Codigo_USR' AND `Tabla_CNS`='itusuarios' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ADM' AND `Tabla_CNS`='gxadmision' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_EGR' AND `Tabla_CNS`='gxegresos' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_HCM' AND `Tabla_CNS`='hcordenesmedica' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ISF' AND `Tabla_CNS`='czinvsolfarmacia' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_NCT' AND `Tabla_CNS`='cznotascontablesenc' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ORD' AND `Tabla_CNS`='gxordenescab' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_RAD' AND `Tabla_CNS`='czradicacionescab' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_TER' AND `Tabla_CNS`='czterceros' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ARE' AND `Tabla_CNS`='czareas' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_EPS' AND `Tabla_CNS`='gxeps' AND `Codigo_DCD`=0;
UPDATE `czcentrocosto` SET `Nombre_CCT`='Consulta Externa' WHERE  `Codigo_CCT`='1' AND `Codigo_DCD`=0;
DELETE FROM hcfolios;
DELETE FROM hcantecedentes;
DELETE FROM hcdiagnosticos;
DELETE FROM hcmedpacientes;
DELETE FROM hcnotas;
DELETE FROM hcordenesdx;
DELETE FROM hcordenesmedica;
DELETE FROM hcordenesservicios;
DELETE FROM hcsignosvitales;
DELETE FROM hctratamiento;
DELETE FROM hcusuarioshc;
DELETE FROM hc_ENFERMERIA;
DELETE FROM hc_EVOL1;
DELETE FROM hc_HC01;
DELETE FROM hc_HCPSQ;
DELETE FROM hc_NNUTRI;
DELETE FROM hc_NPSICO;
DELETE FROM hc_TFEVOL;
DELETE FROM hc_TFIS1;
DELETE FROM hc_TFONEV;
DELETE FROM hc_TOCU1;
DELETE FROM hc_TOEVOL;
DELETE FROM hc_TRESP1;
DELETE FROM hc_TREVOL;
DELETE FROM hc_TREVTRQ;
DELETE FROM itauditoria;
DELETE FROM itusuariosbodegas;
DELETE FROM itusuariossedes;
DELETE FROM itmensajes;
Delete from czmovcajadet;
Delete from czmovcajaenc;
Delete from czmovcajadiario;
Delete from gxcitasmedicas;
Delete from gxcitasreprogramadas;
Delete from gxagendadet;
Delete from gxagendacab;
Delete from gxconsultorios;
Delete from gxareas;
INSERT INTO gxareas (`Codigo_ARE`, `Nombre_ARE`, `Salida_ARE`, `Traslados_ARE`, `AgendaCitas_ARE`, `HoraIni_ARE`, `HoraFin_ARE`, `TiempoConsulta_ARE`) VALUES ('CX', 'CONSULTA EXTERNA', '0', '0', '1', '07:30:00', '18:00:00', '20');
INSERT INTO gxconsultorios (`Codigo_DCD`, `Codigo_CNS`, `Nombre_CNS`, `Descripcion_CNS`, `Codigo_ARE`) VALUES ('0', 'CONS001', 'Consultorio 1', 'Consultorio 1', 'CX');
Delete from gxfacturascapita;
UPDATE itconsecutivos SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_CIT' AND `Tabla_CNS`='gxcitasmedicas' AND `Codigo_DCD`=0;
UPDATE itconsecutivos SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_AGE' AND `Tabla_CNS`='gxagendacab' AND `Codigo_DCD`=0;
UPDATE itconsecutivos SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_HCS' AND `Tabla_CNS`='hcordenesdx' AND `Codigo_DCD`=0;
UPDATE itconsecutivos SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_MCJ' AND `Tabla_CNS`='czmovcajaenc' AND `Codigo_DCD`=0;
Drop table itauditoria;
CREATE TABLE itauditoria (	`Codigo_AUD` INT(10) NOT NULL AUTO_INCREMENT,	`Codigo_USR` VARCHAR(4) NULL DEFAULT NULL,	`Fecha_AUD` DATETIME NULL DEFAULT NULL,	`Codigo_ACT` INT(2) NULL DEFAULT NULL,	`Codigo_APP` INT(2) NULL DEFAULT NULL,	`Registro_AUD` VARCHAR(50) NULL DEFAULT NULL,	`Descripcion_AUD` VARCHAR(255) NULL DEFAULT NULL,	`BrowserName_AUD` VARCHAR(30) NULL DEFAULT NULL,	`BrowserVersion_AUD` VARCHAR(15) NULL DEFAULT NULL,	`Plataforma_AUD` VARCHAR(30) NULL DEFAULT NULL,	`Equipo_AUD` VARCHAR(30) NULL DEFAULT NULL,	`Direccion_AUD` VARCHAR(15) NULL DEFAULT NULL,	PRIMARY KEY (`Codigo_AUD`),	UNIQUE INDEX `Codigo_USR_Fecha_AUD` (`Codigo_USR`, `Fecha_AUD`),	INDEX `Fecha_AUD` (`Fecha_AUD`),	INDEX `Codigo_USR` (`Codigo_USR`)) COMMENT='Auditoría de las actividades de los usuarios en el sistema.' COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=0;
Delete from itfavoritos;
