UPDATE `itconfig` SET `Version_DCD`='19.02.16.001';
UPDATE `itmodulos` SET `Icono_MOD`='nexus-it.co' WHERE  `Codigo_MOD`=0 AND `Codigo_APP`=0;
UPDATE `itmodulos` SET `Descripcion_MOD`='Parametros Nexus-it Apps Systems' WHERE  `Codigo_MOD`=0 AND `Codigo_APP`=0;
UPDATE `itmodulos` SET `Icono_MOD`='fa-file-text' WHERE  `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `itmodulos` SET `Icono_MOD`='fa-users' WHERE  `Codigo_MOD`=2 AND `Codigo_APP`=10;
UPDATE `itmodulos` SET `Nombre_MOD`='Reportes', `Descripcion_MOD`='Reportes' WHERE  `Codigo_MOD`=2 AND `Codigo_APP`=10;
UPDATE `itmenu` SET `Nombre_MNU`='Configuración' WHERE  `Codigo_MNU`=103 AND `Codigo_APP`=10 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Nombre_MNU`='Cotizaciones' WHERE  `Codigo_MNU`=104 AND `Codigo_APP`=10 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Nombre_MNU`='Emisiones' WHERE  `Codigo_MNU`=105 AND `Codigo_APP`=10 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Codigo_MOD`='1', `Nombre_MNU`='Reimpresiones' WHERE  `Codigo_MNU`=106 AND `Codigo_APP`=10 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Cotizaciones' WHERE  `Codigo_MNU`=107 AND `Codigo_APP`=10 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Ventas' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=10 AND `Codigo_MOD`=2;
ALTER TABLE `itmenu`	ADD COLUMN `FontLogo_MNU` VARCHAR(50) NOT NULL DEFAULT 'fa fa-cog' AFTER `Descripcion_MNU`;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-cogs' WHERE  `Codigo_MNU`=103 AND `Codigo_APP`=10 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-plane' WHERE  `Codigo_MNU`=105 AND `Codigo_APP`=10 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-print' WHERE  `Codigo_MNU`=106 AND `Codigo_APP`=10 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-pie-chart' WHERE  `Codigo_MNU`=107 AND `Codigo_APP`=10 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-line-chart' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=10 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Parámetros' WHERE  `Codigo_MNU`=13 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=14 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=15 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-play' WHERE  `Codigo_MNU`=13 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itperfiles` SET `Nombre_PRF`='PROMOTOR' WHERE  `Codigo_PRF`=4 AND `Codigo_DCD`=0;
UPDATE `itperfiles` SET `Nombre_PRF`='CLIENTE', `Activo_PRF`='0' WHERE  `Codigo_PRF`=3 AND `Codigo_DCD`=0;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('479', '103', '1', '10', 'Modalidades');
UPDATE `ititems` SET `Codigo_MNU`='105' WHERE  `Codigo_ITM`=388 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='105' WHERE  `Codigo_ITM`=390 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='106' WHERE  `Codigo_ITM`=393 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='106' WHERE  `Codigo_ITM`=418 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Nueva Cotización' WHERE  `Codigo_ITM`=387 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Anular Cotización' WHERE  `Codigo_ITM`=389 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Editar Póliza' WHERE  `Codigo_ITM`=432 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Nueva Emisión' WHERE  `Codigo_ITM`=388 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Anular Emisión' WHERE  `Codigo_ITM`=390 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Pólizas' WHERE  `Codigo_ITM`=393 AND `Codigo_MNU`=106 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Certificaciones' WHERE  `Codigo_ITM`=418 AND `Codigo_MNU`=106 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='108' WHERE  `Codigo_ITM`=391 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='108' WHERE  `Codigo_ITM`=392 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='107' WHERE  `Codigo_ITM`=402 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='107' WHERE  `Codigo_ITM`=403 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MNU`='107' WHERE  `Codigo_ITM`=404 AND `Codigo_MNU`=105 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MOD`='2' WHERE  `Codigo_ITM`=392 AND `Codigo_MNU`=108 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MOD`='2' WHERE  `Codigo_ITM`=402 AND `Codigo_MNU`=107 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MOD`='2' WHERE  `Codigo_ITM`=403 AND `Codigo_MNU`=107 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MOD`='2' WHERE  `Codigo_ITM`=404 AND `Codigo_MNU`=107 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Codigo_MOD`='2' WHERE  `Codigo_ITM`=391 AND `Codigo_MNU`=108 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Reporte Gral de Cotizaciones' WHERE  `Codigo_ITM`=402 AND `Codigo_MNU`=107 AND `Codigo_MOD`=2 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Reporte Gral de Ventas' WHERE  `Codigo_ITM`=391 AND `Codigo_MNU`=108 AND `Codigo_MOD`=2 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Individual' WHERE  `Codigo_ITM`=396 AND `Codigo_MNU`=103 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Pareja' WHERE  `Codigo_ITM`=397 AND `Codigo_MNU`=103 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
UPDATE `ititems` SET `Nombre_ITM`='Familia' WHERE  `Codigo_ITM`=398 AND `Codigo_MNU`=103 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
