DELETE FROM czempleados;
DELETE FROM czcajas;
DELETE FROM czinvsolfarmacia;
DELETE FROM gxordenesdet;
DELETE FROM gxordenescab;
DELETE FROM gxconsultorios;
DELETE FROM itusuariosareas;
DELETE FROM itusuariossedes;
DELETE FROM itusuarios WHERE  Codigo_USR NOT IN ('0','1','3','2');
DELETE FROM gxareas;
DELETE FROM czsedes;
DELETE FROM gxadmision;
DELETE FROM gxadmcovid19;
DELETE FROM gxagendadet;
DELETE FROM gxagendacab;
DELETE FROM gxpacientes WHERE codigo_ter NOT IN (0,1);
DELETE FROM czterceros WHERE codigo_ter NOT IN ('0','1', 'X');
DELETE FROM gxcitasmedicas;
DELETE FROM gxcitasreprogramadas;
DELETE FROM gxcontratos WHERE  Codigo_EPS<>'0';
DELETE FROM gxeps WHERE  Codigo_EPS<>'0';
DELETE FROM gxestancias;
DELETE FROM gxpabelloncamas;
DELETE FROM gxmedicos;
DELETE FROM gxmedicosesp;
DELETE FROM gxpaquetes;
DELETE FROM gxprgmpctes;
DELETE FROM hcanalisis;
DELETE FROM hcant_alergico;
DELETE FROM hcant_familiar;
DELETE FROM hcant_ginecobst;
DELETE FROM hcant_personales;
DELETE FROM hcant_toxicologico;
DELETE FROM hcctrlparaobs;
DELETE FROM hcctrlprentl;
DELETE FROM hcdiagnosticos;
DELETE FROM hcembactual;
DELETE FROM hcfolios;
DELETE FROM hcfolios_old;
DELETE FROM hcframingham;
DELETE FROM hcidriesgoesp;
DELETE FROM hcincapacidades;
DELETE FROM hclabsrcv;
DELETE FROM hcnotas;
DELETE FROM hcordenesdx;
DELETE FROM hcordenesmedica;
DELETE FROM hcordenesqx;
DELETE FROM hcordenesservicios;
DELETE FROM hcriegocv;
DELETE FROM hcriegoobs;
DELETE FROM hcsignosvitales;
DELETE FROM hctratamiento;
DELETE FROM hcusuarioshc;
DELETE FROM itauditoria;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ADM' AND `Tabla_CNS`='gxadmision' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_AGE' AND `Tabla_CNS`='gxagendacab' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_CIT' AND `Tabla_CNS`='gxcitasmedicas' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_CNS' AND `Tabla_CNS`='gxconsultorios' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_EPS' AND `Tabla_CNS`='gxeps' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_EXA' AND `Tabla_CNS`='lbexamenes' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_GRC' AND `Tabla_CNS`='gxgrupocamas' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_HCM' AND `Tabla_CNS`='hcordenesmedica' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_HCS' AND `Tabla_CNS`='hcordenesdx' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ISF' AND `Tabla_CNS`='czinvsolfarmacia' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='0' WHERE  `Campo_CNS`='Codigo_ORD' AND `Tabla_CNS`='gxordenescab' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='1' WHERE  `Campo_CNS`='Codigo_TER' AND `Tabla_CNS`='czterceros' AND `Codigo_DCD`=0;
UPDATE `itconsecutivos` SET `Consecutivo_CNS`='3' WHERE  `Campo_CNS`='Codigo_USR' AND `Tabla_CNS`='itusuarios' AND `Codigo_DCD`=0;
