UPDATE `itreports` SET `SQL_RPT`='Select\r\n K.Codigo_RAD,  DATE_FORMAT(L.FechaConf_RAD, \'%d/%m/%Y\'), D.Codigo_FAC, DATE_FORMAT(D.Fecha_FAC, \'%d/%m/%Y\'),LPAD(A.Codigo_ADM,10,\'0\'), concat(Q.Sigla_TID,\' \',C.ID_TER), left(C.Nombre_TER, 60), \r\n J.Descripcion_ADM, E.Codigo_EPS, F.Nombre_TER, concat(\'{\',I.Codigo_USR,\'} \', I.ID_USR), D.ValPaciente_FAC, D.ValEntidad_FAC, D.ValCredito_FAC, (D.ValPaciente_FAC+ D.ValEntidad_FAC - D.ValCredito_FAC) \r\nFrom\r\n czterceros AS C, gxeps AS E, czterceros AS F, cztipoid as Q, \r\n itusuarios AS I, gxtipoingreso AS J, gxadmision AS A, gxfacturas AS D,\r\n czradicacionesdet AS K, czradicacionescab AS L \r\nWhere\r\n L.Codigo_RAD=K.Codigo_RAD and D.Codigo_FAC=K.Codigo_FAC and A.Codigo_TER = C.Codigo_TER \r\n AND Q.Codigo_TID = C.Codigo_TID and D.Codigo_ADM=A.Codigo_ADM\r\n AND F.Codigo_TER = E.Codigo_TER AND trim(D.Codigo_EPS) = trim(E.Codigo_EPS) \r\n AND D.Codigo_USR = I.Codigo_USR AND J.Tipo_ADM = A.Ingreso_ADM and D.Estado_FAC=\'1\'\r\n AND L.Estado_RAD=\'2\'\r\n AND L.FechaConf_RAD>=\'@FECHA_INICIAL 00:00:00\' AND L.FechaConf_RAD<=\'@FECHA_FINAL 23:59:59\'\r\nOrder By\r\nL.Codigo_RAD, L.FechaConf_RAD, D.Codigo_FAC' WHERE  `Codigo_RPT`='radicadofecha' AND `Codigo_DCD`=0;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('413', '52', '3', '2', 'Ingresos sin Servicios Cargados', 'reports/ingsinordenserv.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('414', '52', '3', '2', 'Facturas Anuladas', 'reports/factanuladas.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('415', '52', '3', '2', 'Notas Credito por Periodo', 'reports/notascredfecha.php');
UPDATE `ititems` SET `Nombre_ITM`='Facturas Anuladas por Periodo' WHERE  `Codigo_ITM`=414 AND `Codigo_MNU`=52 AND `Codigo_MOD`=3 AND `Codigo_APP`=2;
UPDATE `itreports` SET `SQL_RPT`='select a.Codigo_ADM, f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, b.Codigo_SEX, \r\nTIMESTAMPDIFF(YEAR, b.FechaNac_PAC, CURDATE()), b.FechaNac_PAC, d.Nombre_MUN, a.Autorizacion_ADM, c.Direccion_TER, c.Telefono_TER,\r\ndate(a.Fecha_ADM), g.Codigo_DGN, sum(i.Cantidad_ORD), j.Nombre_SER, a.Codigo_SDE, a.estado_adm\r\nFrom gxadmision a, gxpacientes b, czterceros c, czmunicipios d, czdepartamentos e, cztipoid f, gxdiagnostico g, gxordenescab h, gxordenesdet i, gxservicios j\r\nWhere a.Codigo_TER=b.Codigo_TER and b.Codigo_TER=c.Codigo_TER and d.Codigo_MUN=b.Codigo_MUN and d.Codigo_DEP=b.Codigo_DEP and h.Codigo_ORD=i.Codigo_ORD and h.Codigo_ADM=a.Codigo_ADM and h.Estado_ORD=\'1\' and Estado_ADM<>\'A\'  \r\nand j.Codigo_SER=i.Codigo_SER and e.Codigo_DEP=b.Codigo_DEP and f.Codigo_TID=c.Codigo_TID and g.Codigo_DGN=a.Codigo_DGN and a.Fecha_ADM>=\'@FECHA_INICIAL\' and a.Fecha_ADM<=\'@FECHA_FINAL 23:59:59\' and a.Codigo_EPS=\'@ENTIDAD\'\r\nGroup by f.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, b.Codigo_SEX, \r\nTIMESTAMPDIFF(YEAR, b.FechaNac_PAC, CURDATE()), b.FechaNac_PAC, d.Nombre_MUN, a.Autorizacion_ADM, c.Direccion_TER, c.Telefono_TER,\r\ndate(a.Fecha_ADM), g.Descripcion_DGN, j.Nombre_SER, a.Codigo_SDE, a.estado_adm\r\nOrder by 4, 5, 6' WHERE  `Codigo_RPT`='autorizaciones' AND `Codigo_DCD`=0;
ALTER TABLE `klconfig`	ADD COLUMN `Vigencia_KLD` INT NULL COMMENT 'Dias validos para cotizacion' AFTER `PrefPoliza_KLD`;
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`) VALUES ('ingsinordenserv', 'Ingresos Sin Ordenes de Servicios');
UPDATE `itreports` SET `SQL_RPT`='Select a.Codigo_ADM, a.Fecha_ADM, x.ID_TER, x.Nombre_TER, y.Nombre_EPS, a.Motivo_ADM\r\nFrom czterceros x, gxeps y, gxadmision a\r\nLeft Outer Join gxordenescab b\r\nON   a.Codigo_ADM = b.Codigo_ADM\r\nwhere b.Codigo_ADM is null\r\nand x.Codigo_TER=a.Codigo_TER and y.Codigo_EPS=a.Codigo_EPS\r\nand a.Estado_ADM=\'I\'\r\nand a.Fecha_ADM between \'@FECHA_INICIAL 00:00:00\' and \'@FECHA_FINAL 23:59:59\'' WHERE  `Codigo_RPT`='ingsinordenserv' AND `Codigo_DCD`=0;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('ingsinordenserv', 'FECHA_INICIAL', 'Fecha Inicial', '2', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('ingsinordenserv', 'FECHA_FINAL', 'Fecha Final', '3', 'D');
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`) VALUES ('factanuladas', 'Facturas anuladas por periodo');
UPDATE `itreports` SET `SQL_RPT`='Select\r\n D.Codigo_FAC, DATE_FORMAT(D.Fecha_FAC, \'%d/%m/%Y\'),LPAD(A.Codigo_ADM,10,\'0\'), concat(Q.Sigla_TID,\' \',C.ID_TER), left(C.Nombre_TER, 60), \r\n J.Descripcion_ADM, E.Codigo_EPS, F.Nombre_TER, concat(\'{\',I.Codigo_USR,\'} \', I.ID_USR), D.ValPaciente_FAC, D.ValEntidad_FAC, D.MotivoAnula_FAC, D.ValCredito_FAC, D.ValTotal_FAC \r\nFrom\r\n czterceros AS C, gxeps AS E, czterceros AS F, cztipoid as Q, \r\n itusuarios AS I, gxtipoingreso AS J, gxadmision AS A, gxfacturas AS D \r\n left join czradicacionesdet AS K On D.Codigo_FAC=K.Codigo_FAC \r\nWhere\r\n A.Codigo_TER = C.Codigo_TER AND Q.Codigo_TID = C.Codigo_TID and D.Codigo_ADM=A.Codigo_ADM\r\n AND F.Codigo_TER = E.Codigo_TER AND trim(D.Codigo_EPS) = trim(E.Codigo_EPS) \r\n AND D.UsuarioAnula_FAC = I.Codigo_USR AND J.Tipo_ADM = A.Ingreso_ADM and D.Estado_FAC=\'0\'\r\n AND D.FechaAnula_FAC>=\'@FECHA_INICIAL 00:00:00\' AND D.FechaAnula_FAC<=\'@FECHA_FINAL 23:59:59\'\r\nOrder By\r\nD.Fecha_FAC, D.Codigo_FAC' WHERE  `Codigo_RPT`='factanuladas' AND `Codigo_DCD`=0;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('factanuladas', 'FECHA_FINAL', 'Fecha Final', '2', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('factanuladas', 'FECHA_INICIAL', 'Fecha Inicial', '1', 'D');

INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('416', '103', '1', '10', 'Actualizar TRM', 'forms/trmupdate.php');
UPDATE `itreports` SET `SQL_RPT`='Select a.Razonsocial_DCD, a.NIT_DCD, a.Direccion_DCD, a.Telefonos_DCD, a.EncabezadoFact_DCD, a.PiePaginaFact_DCD, \n b.ConsecIni_AFC, b.ConsecFin_AFC, b.Resolucion_AFC, b.Fecha_AFC, c.Codigo_FAC, c.Codigo_ADM, c.Fecha_FAC, c.ValPaciente_FAC, \n c.ValEntidad_FAC, c.ValDcto_FAC, c.Estado_FAC, CONCAT(e.ID_TER,\'-\',e.DigitoVerif_TER), e.Nombre_TER, e.Direccion_TER, e.Telefono_TER, \n LPAD(f.Codigo_ADM,10,\'0\'), CONCAT(h.Sigla_TID,\' \', g.ID_TER), g.Nombre_TER, i.Nombre_PLA, c.Codigo_EPS, c.Codigo_PLA, adddate(c.Fecha_FAC,d.VenceFactura_EPS), f.Autorizacion_ADM, a.Ciudad_DCD, g.Direccion_TER, g.Telefono_TER, Barrio_PAC, Nombre_MUN, x.Codigo_DGN, x.Descripcion_DGN, Prefijo_AFC, ValCredito_FAC, f.fecha_adm, f.FechaFin_ADM  \nFrom itconfig a, czautfacturacion b, gxfacturas c, gxeps d, czterceros e, gxadmision f, czterceros g, cztipoid h, gxplanes i, gxpacientes p, czmunicipios m, gxdiagnostico x \nWhere x.Codigo_DGN=f.Codigo_DGN and m.Codigo_MUN=p.Codigo_MUN and m.Codigo_DEP=p.Codigo_DEP and c.Codigo_AFC = b.Codigo_AFC and \np.Codigo_TER=g.Codigo_TER and d.Codigo_EPS= c.Codigo_EPS and e.Codigo_TER= d.Codigo_TER and f.Codigo_ADM =c.Codigo_ADM \n and g.Codigo_TER=f.Codigo_TER and h.Codigo_TID=g.Codigo_TID and i.Codigo_PLA= c.Codigo_PLA\n and c.Codigo_FAC>=Concat(\'@PREFIJO\',\' \',LPAD(\'@CODIGO_INICIAL\',10,\'0\')) and c.Codigo_FAC<=Concat(\'@PREFIJO\',\' \',LPAD(\'@CODIGO_FINAL\',10,\'0\'));' WHERE  `Codigo_RPT`='facturasaluddet' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='Select a.Razonsocial_DCD, a.NIT_DCD, a.Direccion_DCD, a.Telefonos_DCD, a.EncabezadoFact_DCD, a.PiePaginaFact_DCD, \n b.ConsecIni_AFC, b.ConsecFin_AFC, b.Resolucion_AFC, b.Fecha_AFC, c.Codigo_FAC, c.Codigo_ADM, c.Fecha_FAC, c.ValPaciente_FAC, \n c.ValEntidad_FAC, c.ValDcto_FAC, c.Estado_FAC, CONCAT(e.ID_TER,\'-\',e.DigitoVerif_TER), e.Nombre_TER, e.Direccion_TER, e.Telefono_TER, \n LPAD(f.Codigo_ADM,10,\'0\'), CONCAT(h.Sigla_TID,\' \', g.ID_TER), g.Nombre_TER, i.Nombre_PLA, c.Codigo_EPS, c.Codigo_PLA, adddate(c.Fecha_FAC,d.VenceFactura_EPS), f.Autorizacion_ADM, a.Ciudad_DCD, g.Direccion_TER, g.Telefono_TER, Barrio_PAC, Nombre_MUN, x.Codigo_DGN, x.Descripcion_DGN, Prefijo_AFC, ValCredito_FAC, date(f.fecha_adm), f.FechaFin_ADM  \nFrom itconfig a, czautfacturacion b, gxfacturas c, gxeps d, czterceros e, gxadmision f, czterceros g, cztipoid h, gxplanes i, gxpacientes p, czmunicipios m, gxdiagnostico x \nWhere x.Codigo_DGN=f.Codigo_DGN and m.Codigo_MUN=p.Codigo_MUN and m.Codigo_DEP=p.Codigo_DEP and c.Codigo_AFC = b.Codigo_AFC and \np.Codigo_TER=g.Codigo_TER and d.Codigo_EPS= c.Codigo_EPS and e.Codigo_TER= d.Codigo_TER and f.Codigo_ADM =c.Codigo_ADM \n and g.Codigo_TER=f.Codigo_TER and h.Codigo_TID=g.Codigo_TID and i.Codigo_PLA= c.Codigo_PLA\n and c.Codigo_FAC>=Concat(\'@PREFIJO\',\' \',LPAD(\'@CODIGO_INICIAL\',10,\'0\')) and c.Codigo_FAC<=Concat(\'@PREFIJO\',\' \',LPAD(\'@CODIGO_FINAL\',10,\'0\'));' WHERE  `Codigo_RPT`='facturasaluddet' AND `Codigo_DCD`=0;

INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`, `SQL_RPT`) VALUES ('listarnotascreditofecha', 'Notas Credito por periodo', 'Select\r\n D.Codigo_FAC, DATE_FORMAT(D.Fecha_FAC, \'%d/%m/%Y\'),LPAD(A.Codigo_ADM,10,\'0\'), concat(Q.Sigla_TID,\' \',C.ID_TER), left(C.Nombre_TER, 60), \r\n J.Descripcion_ADM, E.Codigo_EPS, F.Nombre_TER, concat(\'{\',I.Codigo_USR,\'} \', I.ID_USR), D.ValPaciente_FAC, D.ValEntidad_FAC, D.MotivoAnula_FAC, D.ValCredito_FAC, D.ValTotal_FAC \r\nFrom\r\n czterceros AS C, gxeps AS E, czterceros AS F, cztipoid as Q, \r\n itusuarios AS I, gxtipoingreso AS J, gxadmision AS A, gxfacturas AS D \r\n left join czradicacionesdet AS K On D.Codigo_FAC=K.Codigo_FAC \r\nWhere\r\n A.Codigo_TER = C.Codigo_TER AND Q.Codigo_TID = C.Codigo_TID and D.Codigo_ADM=A.Codigo_ADM\r\n AND F.Codigo_TER = E.Codigo_TER AND trim(D.Codigo_EPS) = trim(E.Codigo_EPS) \r\n AND D.UsuarioAnula_FAC = I.Codigo_USR AND J.Tipo_ADM = A.Ingreso_ADM and D.Estado_FAC=\'0\'\r\n AND D.FechaAnula_FAC>=\'@FECHA_INICIAL 00:00:00\' AND D.FechaAnula_FAC<=\'@FECHA_FINAL 23:59:59\'\r\nOrder By\r\nD.Fecha_FAC, D.Codigo_FAC');
UPDATE `ititems` SET `Enlace_ITM`='reports/listarnotascreditofecha.php' WHERE  `Codigo_ITM`=415 AND `Codigo_MNU`=52 AND `Codigo_MOD`=3 AND `Codigo_APP`=2;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('listarnotascreditofecha', 'FECHA_INICIAL', 'Fecha Inicial', '1', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('listarnotascreditofecha', 'FECHA_FINAL', 'Fecha Final', '2', 'D');
UPDATE `itreports` SET `SQL_RPT`='Select\r\n LPAD(A.Codigo_NCT ,10,\'0\'), DATE_FORMAT(A.Fecha_NCT, \'%d/%m/%Y\'), A.NumeroDoc_NCT, DATE_FORMAT(D.Fecha_FAC, \'%d/%m/%Y\'), concat(Q.Sigla_TID,\' \',C.ID_TER), left(C.Nombre_TER, 60),\r\n E.Codigo_EPS, F.Nombre_TER, A.Valor_NCT , D.ValTotal_FAC , concat(\'{\',I.Codigo_USR,\'} \', I.ID_USR)\r\nFrom\r\n czterceros AS C, gxeps AS E, czterceros AS F, cztipoid as Q, \r\n itusuarios AS I, cznotascontablesenc AS A, gxfacturas AS D \r\nWhere\r\n A.Codigo_TER = C.Codigo_TER AND Q.Codigo_TID = C.Codigo_TID \r\n AND F.Codigo_TER = E.Codigo_TER AND trim(D.Codigo_EPS) = trim(E.Codigo_EPS) \r\n AND A.Codigo_USR = I.Codigo_USR and A.Naturaleza_NCT=\'C\' And A.NumeroDoc_NCT=D.Codigo_FAC\r\n AND A.Fecha_NCT >=\'@FECHA_INICIAL 00:00:00\' AND A.Fecha_NCT <=\'@FECHA_FINAL 23:59:59\' \r\nOrder By\r\nA.Codigo_NCT' WHERE  `Codigo_RPT`='listarnotascreditofecha' AND `Codigo_DCD`=0;
