CREATE TABLE `gxpacientestipos` ( 	`Codigo_DCD` INT(5) NOT NULL DEFAULT '0', 	`Codigo_PTT` VARCHAR(3) NOT NULL DEFAULT '0', 	`Nombre_PTT` VARCHAR(60) NULL DEFAULT NULL, `Reingreso_PTT` VARCHAR(3) NULL DEFAULT NULL COMMENT 'Puede generar un nuevo ingreso al liquidar la cuenta', 	`Estado_ARE` CHAR(1) NULL DEFAULT '1', 	PRIMARY KEY (`Codigo_PTT`, `Codigo_DCD`), 	INDEX `Codigo_CCT` (`Reingreso_PTT`) ) COMMENT='Clasificacion de pacientes en el ingreso' COLLATE='utf8_general_ci' ENGINE=InnoDB;
ALTER TABLE `gxadmision` ADD COLUMN `Codigo_PTT` VARCHAR(3) NULL DEFAULT '0' AFTER `Codigo_SDE`, 	ADD INDEX `Codigo_PTT` (`Codigo_PTT`), 	ADD INDEX `Codigo_SDE` (`Codigo_SDE`); 
INSERT INTO `gxpacientestipos` (`Codigo_PTT`, `Nombre_PTT`) VALUES ('1', 'Crónico');
INSERT INTO `gxpacientestipos` (`Codigo_PTT`, `Nombre_PTT`, `Reingreso_PTT`) VALUES ('2', 'Agudo', '0');
UPDATE `ititems` SET `Icono_ITM`='1.PatientData.png' WHERE  `Codigo_ITM`=323 AND `Codigo_MNU`=48 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
CREATE TABLE `gxtipoatencion` (	`Codigo_DCD` INT(5) NOT NULL DEFAULT '0',	`Codigo_ATE` VARCHAR(3) NOT NULL DEFAULT '0',	`Nombre_ATE` VARCHAR(60) NULL DEFAULT NULL,	`Estado_ATE` CHAR(1) NULL DEFAULT '1',	PRIMARY KEY (`Codigo_ATE`, `Codigo_DCD`)) COMMENT='Tipo de Atencion en el ingreso' COLLATE='utf8_general_ci' ENGINE=InnoDB;
INSERT INTO `gxtipoatencion` (`Codigo_ATE`) VALUES ('1');
UPDATE `gxtipoatencion` SET `Nombre_ATE`='OXIGENODEPENDIENTE' WHERE  `Codigo_ATE`='1' AND `Codigo_DCD`=0;
INSERT INTO `gxtipoatencion` (`Codigo_ATE`, `Nombre_ATE`) VALUES ('2', 'CUIDADOS PALIATIVOS');
INSERT INTO `gxtipoatencion` (`Codigo_ATE`, `Nombre_ATE`) VALUES ('3', 'APLICACION DE MEDICAMENTOS');
INSERT INTO `gxtipoatencion` (`Codigo_ATE`, `Nombre_ATE`) VALUES ('4', 'CURACIONES');
INSERT INTO `gxtipoatencion` (`Codigo_ATE`, `Nombre_ATE`) VALUES ('5', 'REHABILITACION INTEGRAL');
ALTER TABLE `gxadmision` ADD COLUMN `Codigo_ATE` VARCHAR(3) NULL DEFAULT '0' AFTER `Codigo_PTT`;
/*---------------------*/
CREATE TABLE `hc_ENFERMERIA` (	`Codigo_TER` CHAR(10) NOT NULL COLLATE 'latin1_swedish_ci',	`Codigo_HCF` INT(11) NOT NULL,	`curacion_HC` VARCHAR(1) NULL DEFAULT '0' COMMENT 'Tipo Curacion',	`dispositivo_HC` VARCHAR(6) NULL DEFAULT '' COMMENT 'Cambio Dispositivo',	`nota_HC` TEXT NULL COMMENT 'Nota de Enfermeria',	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`),	INDEX `Codigo_TER` (`Codigo_TER`),	INDEX `Codigo_HCF` (`Codigo_HCF`)) COMMENT='FORMATO REGISTRO DE ENFERMERIA' COLLATE='utf8_general_ci' ENGINE=InnoDB;
ALTER TABLE `hc_ENFERMERIA` 	CHANGE COLUMN `nota_HC` `nota_HC` TEXT NULL COMMENT 'Nota de Enfermeria' AFTER `dispositivo_HC`;
UPDATE `hccampos` SET `Orden_HCC`=3 WHERE  `Codigo_HCT`='ENFERMERIA' AND `Codigo_HCC`='nota';
UPDATE `hccampos` SET `Orden_HCC`=2 WHERE  `Codigo_HCT`='ENFERMERIA' AND `Codigo_HCC`='dispositivo';
UPDATE `hccampos` SET `Orden_HCC`=1 WHERE  `Codigo_HCT`='ENFERMERIA' AND `Codigo_HCC`='curacion';

INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'localizacion', 'Localización', 1, 'Localización', 12, 1, 255, '1');
SELECT `Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Defecto_HCC`, `Normalizar_HCC`, `Grupo_HCC`, `Obligatorio_HCC`, `Parametros_HCC` FROM `hccampos` WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='como';
UPDATE `hccampos` SET `Largo_HCC`=7 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='localizacion';
UPDATE `hccampos` SET `Lineas_HCC`=1, `Maximo_HCC`=2, `Obligatorio_HCC`='1' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='como';
UPDATE `hccampos` SET `Nombre_HCC`='Localizacion' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='localizacion';
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'como', 1, 'PRESENTE', 'PRESENTE EN LA ADMISION');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'como', 2, 'ADQUIRIDA', 'ADQUIRIDA');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'tamano', 'Tamaño', 3, 'Tamaño', 'well', 12, 0, 0);
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'longitud', 'Longitud', 4, 'Longitud (cm)', 4, 1, 10, '3', '1');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'anchura', 'Anchura', 5, 'Anchura (cm)', 4, 1, 10, '3', '1');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'etiologia', 'Etiologia', 7, 'Etiología', 'select', 4, 1, 2, '1');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 1, 'PRESION', 'POR PRESION');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 2, 'VENOSA', 'VENOSA');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 3, 'DIABETICA', 'DIABETICA');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 4, 'ARTERIAL', 'ARTERIAL');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 5, 'MIXTA', 'MIXTA ARTERIAL-VENOSA');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 6, 'QUIRURGICA', 'QUIRURGICA');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'etiologia', 7, ' ', 'OTRA');
UPDATE `hccamposlistas` SET `Valor_HCC`='' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='etiologia' AND `Orden_HCC`=7;
UPDATE `hccampos` SET `Parametros_HCC`='onchange="javascript: if (this.value!=\'\') { $(\'#txt_otraetiologia.WINDOW.\').attr(\'disabled\',\'disabled\'); } else { $(\'#txt_otraetiologia.WINDOW.\').removeAttr(\'disabled\'); $(\'#txt_otraetiologia.WINDOW.\').focus(); }"' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='etiologia';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Parametros_HCC`) VALUES ('VALHER1', 'otraetiologia', 'Otra', 8, 'Otra', 4, 1, 50, 'disabled="disabled"');
UPDATE `hccampos` SET `Largo_HCC`=3 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='etiologia';
UPDATE `hccampos` SET `Largo_HCC`=2 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='otraetiologia';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'clasificacion', 'Clasificacion', 9, 'Clasificación', 'select', 3, 1, 2);
ALTER TABLE `hccampos`	CHANGE COLUMN `Largo_HCC` `Largo_HCC` INT(11) NULL DEFAULT '12' AFTER `Tipo_HCC`;
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'clasificacion', 1, 'SUPERFICIAL', 'SUPERFICIAL');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'clasificacion', 2, 'GPARCIAL', 'GROSOR PARCIAL');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'clasificacion', 3, 'GTOTAL', 'GROSOR TOTAL');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Lineas_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'lesion', 'Lesion', 10, 'Tipo Lesión', 'select', 1, 2);
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'lesion', 1, 'TIPO1', 'TIPO I');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'lesion', 2, 'TIPO2', 'TIPO II');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'lesion', 3, 'TIPO3', 'TIPO III');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'lesion', 4, 'TIPO4', 'TIPO IV');
UPDATE `hccampos` SET `Largo_HCC`=2 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='lesion';
UPDATE `hccampos` SET `Largo_HCC`=2 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='clasificacion';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`) VALUES ('VALHER1', 'fecha', 'Fecha', 11, 'Fecha en que se observó por primera vez');
UPDATE `hccampos` SET `Largo_HCC`=2 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='fecha';
UPDATE `hccampos` SET `Etiqueta_HCC`='Fecha (observada por 1° vez)' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='fecha';
UPDATE `hccampos` SET `Largo_HCC`=3 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='otraetiologia';
UPDATE `hccampos` SET `Codigo_HCC`='medicion', `Nombre_HCC`='Medicion', `Etiqueta_HCC`='MEDICION' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='tamano';
UPDATE `hccampos` SET `Orden_HCC`=13 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='etiologia';
UPDATE `hccampos` SET `Orden_HCC`=14 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='otraetiologia';
UPDATE `hccampos` SET `Orden_HCC`=15 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='clasificacion';
UPDATE `hccampos` SET `Orden_HCC`=16 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='lesion';
UPDATE `hccampos` SET `Orden_HCC`=17 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='fecha';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'tunelizacion', 'Tunelizacion', 7, 'Tunelización: De', 2, 1, 2, '1');
UPDATE `hccampos` SET `Codigo_HCC`='tunelizacion1', `Nombre_HCC`='Tunelizacion1' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='tunelizacion';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'tunelizacion2', 'Tunelizacion2', 8, 'A', 2, 1, 2, '1');
UPDATE `hccampos` SET `Grupo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='tunelizacion1';
UPDATE `hccampos` SET `Grupo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='tunelizacion2';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'cavidad1', 'Cavidad1', 9, 'Cavidad: De', 2, 1, 2, '3', '1');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'cavidad2', 'Cavidad2', 10, 'A', 2, 1, 2, '3', '1');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`, `Obligatorio_HCC`) VALUES ('VALHER1', 'tracto1', 'Tracto1', 11, 'Tracto Sinusal: De', 2, 1, 2, '3', '1');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Lineas_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'tipotejido', 'TipoTejido', 18, 'Tipo de tejidos observados', 'well', 0, 0);
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'necrotico', 'necrotico', 19, 'TEJIDO NECRÓTICO', 'select', 2, 1, 2, '18');
UPDATE `hccampos` SET `Etiqueta_HCC`='Tejido Necrótico' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='necrotico';
UPDATE `hccampos` SET `Lineas_HCC`=1, `Maximo_HCC`=10 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='fecha';
UPDATE `hccampos` SET `Largo_HCC`=1 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='necrotico';
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'necrotico', 1, 'MENOR25', '< 25%');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'necrotico', 2, 'MAYOR25', '> 25%');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'desbridamiento', 1, 'AUTOLITICO', 'AUTOLITICO');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'desbridamiento', 2, 'ENZIMATICO', 'ENZIMATICO');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'desbridamiento', 3, 'INCISIVOQX', 'INCISIVO/QUIRURGICO');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Lineas_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'desbridamiento', 'Desbridamiento', 20, 'Desbridamiento', 'select', 2, 1, 2, '18');
ALTER TABLE `hccampos`	CHANGE COLUMN `Lineas_HCC` `Lineas_HCC` INT(11) NULL DEFAULT '1' AFTER `Largo_HCC`;
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'escara', 'Escara', 21, '% Escara', 2, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'esfacelo', 'Esfacelo', 22, '% Esfacelo', 2, 2, '18');
UPDATE `hccampos` SET `Etiqueta_HCC`='Porcentaje de tipo de tejidos' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='tipotejido';
UPDATE `hccampos` SET `Etiqueta_HCC`='Escara' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='escara';
UPDATE `hccampos` SET `Etiqueta_HCC`='Esfacelo' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='esfacelo';
UPDATE `hccampos` SET `Largo_HCC`=1 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='esfacelo';
UPDATE `hccampos` SET `Largo_HCC`=1 WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='escara';
UPDATE `hccampos` SET `Grupo_HCC`='0' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='necrotico';
UPDATE `hccampos` SET `Grupo_HCC`='0' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='desbridamiento';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'granulacion', 'Granulacion', 23, 'Granulación', 1, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'Granulacion', 23, 'Granulación', 1, 2, '18');
UPDATE `hccampos` SET `Codigo_HCC`='epitelizacion', `Nombre_HCC`='Epitelizacion', `Orden_HCC`=24, `Etiqueta_HCC`='Epitelización' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'limpio', 'Limpio', 25, 'Limpio no granulado', 1, 2, '18');
UPDATE `hccampos` SET `Etiqueta_HCC`='Limpio' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='limpio';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'hiperg', 'Hipergranulacion', 26, 'Hipergranulación', 1, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'subcutaneo', 'Suncutaneo', 27, 'Subcutáneo', 1, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'tendon', 'Tendon', 28, 'Tendón', 1, 2, '18');
UPDATE `hccampos` SET `Nombre_HCC`='Subcutaneo' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='subcutaneo';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'hueso', 'Hueso', 29, 'Hueso', 1, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'articular', 'Articular', 30, 'Cáps. Articular', 1, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'ampolla', 'Ampolla', 31, 'Ampolla', 1, 2, '18');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'exudadocant', 'ExudadoCant', '32', 'Exudado (Cantidad)', 'select', '2', '2');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadocant', '1', 'SECO', 'SECO, MINIMO');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadocant', '2', 'HUMEDO1', 'HUMEDO, LIGERAMENTE');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadocant', '3', 'HUMEDO2', 'HUMEDO, MODERADAMENTE');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadocant', '4', 'MOJADO', 'MOJADO, ABUNDANTEMENTE');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'exudadotipo', 'ExudadoTipo', '33', 'Exudado (Tipo)', 'select', '2', '2');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadotipo', '1', 'SEROSO', 'SEROSO');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadotipo', '2', 'SEROSANGUINOLENTO', 'SEROSANGUINOLENTO');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadotipo', '3', 'SANGUINOLENTO', 'SANGUINOLENTO');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadotipo', '4', 'ABUNDANTE', 'ABUNDANTE');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'exudadotipo', '5', 'ESCASO', 'ESCASO');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'piel', 'Piel', '34', 'Piel Circundante', 'select', '2', '2');
UPDATE `hccampos` SET `Parametros_HCC`='onchange="javascript: if (this.value!=\'\') { $(\'#txt_otrapiel.WINDOW.\').attr(\'disabled\',\'disabled\'); } else { $(\'#txt_otrapiel.WINDOW.\').removeAttr(\'disabled\'); $(\'#txt_otrapiel.WINDOW.\').focus(); }"' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='piel';
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'piel', '1', 'ENROJECIMIENTO', 'ENROJECIMIENTO/PALIDEZ');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'piel', '2', 'ERITEMA', 'ERITEMA');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'piel', '3', 'HIPERPIGMENTACION', 'HIPERPIGMENTACION');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'piel', '4', 'MACERACION', 'MACERACION');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'piel', '9', '', 'OTRA');
UPDATE `hccampos` SET `Orden_HCC`='35' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='piel';
INSERT INTO `hccampos` (`Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Parametros_HCC`) VALUES ('bordes', 'Piel', '35', 'Piel Circundante', 'select', '2', '2', 'onchange="javascript: if (this.value!=\'\') { $(\'#txt_otrapiel.WINDOW.\').attr(\'disabled\',\'disabled\'); } else { $(\'#txt_otrapiel.WINDOW.\').removeAttr(\'disabled\'); $(\'#txt_otrapiel.WINDOW.\').focus(); }"');
UPDATE `hccampos` SET `Codigo_HCT`='VALHER1', `Orden_HCC`='34', `Etiqueta_HCC`='Bordes de la Herida', `Parametros_HCC`='' WHERE  `Codigo_HCT`='' AND `Codigo_HCC`='bordes';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Largo_HCC`, `Maximo_HCC`, `Parametros_HCC`) VALUES ('VALHER1', 'otrapiel', 'Otra', '36', 'Otra', '1', '50', 'disabled="disabled"');
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'borde', '1', 'IRREGULARES', 'IRREGULARES');
UPDATE `hccamposlistas` SET `Codigo_HCC`='bordes' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='borde' AND `Orden_HCC`=1;
INSERT INTO `hccamposlistas` (`Codigo_HCT`, `Codigo_HCC`, `Orden_HCC`, `Valor_HCC`, `Texto_HCC`) VALUES ('VALHER1', 'bordes', '2', 'DEFINIDOS', 'DEFINIDOS');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Lineas_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'infeccion', 'Infeccion', '37', 'Infección, signos y síntomas', 'well', '0', '0');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec1', 'InfecNo', '38', 'No estan presentes signos ni síntomas', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec2', 'InfecSi', '39', 'Signos y síntomas presentes', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec3', 'InfecDolormas', '40', 'Aumento del dolor', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec4', 'InfecEritema', '41', 'Eritema', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec5', 'InfecEdema', '42', 'Edema', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec6', 'InfecArdor', '43', 'Ardor/Calor', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec7', 'InfecExu', '44', 'Exudado Purulento', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec8', 'InfecCicatr', '45', 'Cicatrización retardada', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec9', 'InfecTejid1', '46', 'Tejido de Granulación Decolorado', 'check', '2', '2', '37');
UPDATE `hccampos` SET `Etiqueta_HCC`='Exudado purulento' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec7';
UPDATE `hccampos` SET `Etiqueta_HCC`='Tejido de granulación decolorado' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec9';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec10', 'InfecTejid2', '47', 'Tejido de granulación friable', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec11', 'InfecBolsa', '48', 'Embolsamiento en la base de la herida', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec12', 'InfecFetido', '49', 'Olor Fétido', 'check', '2', '2', '37');
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Largo_HCC`, `Maximo_HCC`, `Grupo_HCC`) VALUES ('VALHER1', 'infec13', 'InfecDesintr', '50', 'Desintegración de la herida', 'check', '2', '2', '37');
UPDATE `hccampos` SET `Etiqueta_HCC`='Olor fétido' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec12';
INSERT INTO `hccampos` (`Codigo_HCT`, `Codigo_HCC`, `Nombre_HCC`, `Orden_HCC`, `Etiqueta_HCC`, `Tipo_HCC`, `Lineas_HCC`, `Maximo_HCC`) VALUES ('VALHER1', 'observacion', 'Observacion', '51', 'Observaciones', 'textarea', '3', '1000');
UPDATE `hccampos` SET `Largo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec1';
UPDATE `hccampos` SET `Largo_HCC`='1' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec4';
UPDATE `hccampos` SET `Largo_HCC`='1' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec5';
UPDATE `hccampos` SET `Largo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec2';
UPDATE `hccampos` SET `Largo_HCC`='1' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec6';
UPDATE `hccampos` SET `Largo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec10';
UPDATE `hccampos` SET `Largo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec11';
UPDATE `hccampos` SET `Largo_HCC`='3' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec9';
UPDATE `hccampos` SET `Orden_HCC`='48' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec13';
UPDATE `hccampos` SET `Orden_HCC`='50' WHERE  `Codigo_HCT`='VALHER1' AND `Codigo_HCC`='infec11';
