CREATE TABLE `itconfig_fc` (	`CierreDias_XFC` INT NULL DEFAULT '0') COMMENT='Parametros Facturacion' COLLATE='utf8_general_ci' ENGINE=InnoDB ;
UPDATE `ititems` SET `Codigo_ITM`='417' WHERE  `Codigo_ITM`=369 AND `Codigo_MNU`=91 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;

INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('418', '104', '1', '10', 'Reimpresión de Certificaciones', 'reports/klcertificacion.php');
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`, `SQL_RPT`) VALUES ('klcertificaciones', 'Certificaciones Klud', 'Select i.Razonsocial_DCD, i.NIT_DCD, h.Codigo_EMI, date(h.Fecha_EMI), h.Codigo_USR, ID_TER as \'Pasaporte\', Nombre_TER as \'Nombres\', FechaNac_KLI as \'Fecha Nacimiento\', Nombre_AGE as \'Agencia\', Nombre_USR as \'Promotor\', nombre_pla as \'Plan\', Modalidad_CTZ as \'Modalidad\', f.nombre_dst as \'Procedencia\', g.nombre_dst as \'Destino\', FechaIni_CTZ as \'Fecha Inicio\', FechaFin_CTZ as \'Fecha Fin\', Dias_CTZ as \'Días\', TRM_CTZ as \'T.R.M.\', Dolares_CTZ as \'Valor en Dolares\', Pesos_CTZ as \'Valor en Pesos\', Voucher_CTZ as \'Voucher\',a.Direccion_TER, a.Telefono_TER, k.Descripcion_EST as \'Estado\', h.Prefijo_EMI as \'Prefijo\'  \r\nFrom czterceros a, klcotizaciones b, itusuarios c, klagencias d, klplanes e, kldestinos f, kldestinos g, klemisiones h, itconfig i, klclientes j, klestadosventas k  \r\nWhere a.codigo_ter=b.codigo_ter and c.codigo_usr=b.codigo_usr and d.codigo_age=b.codigo_age and e.codigo_pla=b.codigo_pla and j.Codigo_TER=b.Codigo_TER and  \r\nf.codigo_dst=procedencia_ctz and g.codigo_dst=b.codigo_dst and k.Codigo_EST=h.Estado_EMI and\r\nb.codigo_ctz=h.Codigo_CTZ and estado_ctz=\'E\' and LPAD(h.Codigo_EMI,10,\'0\')>=LPAD(\'@EMISION_INICIAL\',10,\'0\') and LPAD(h.Codigo_EMI,10,\'0\')<=LPAD(\'@EMISION_FINAL\',10,\'0\')  and h.Prefijo_EMI<=\'@PREFIJO\' ');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Value_RPT`, `Script_RPT`) VALUES ('klcertificaciones', 'Prefijo', '0', '$value=$_SESSION[\'Kl_Prefijo\'];', ' echo \'onClick="javascript: rpthideoptions\'.$NumWindow.\'();" \';');
UPDATE `itreportsparam` SET `Campo_RPT`='PREFIJO' WHERE  `Codigo_RPT`='klcertificaciones' AND `Campo_RPT`='' AND `Codigo_DCD`=0;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`) VALUES ('klcertificaciones', 'EMISION_INICIAL', 'No Emision Inicial', '1');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`) VALUES ('klcertificaciones', 'EMISION_FINAL', 'No Emision Final', '2');
UPDATE `ititems` SET `Enlace_ITM`='reports/klcertificaciones.php' WHERE  `Codigo_ITM`=418 AND `Codigo_MNU`=104 AND `Codigo_MOD`=1 AND `Codigo_APP`=10;
CREATE TABLE `cztipoglosagral` (	`Codigo_TGG` CHAR(1) NOT NULL,	`Descripcion_TGG` VARCHAR(50) NULL,	`Estado_TGG` CHAR(1) NULL DEFAULT '1',	PRIMARY KEY (`Codigo_TGG`),	INDEX `Descripcion_TGG` (`Descripcion_TGG`),	INDEX `Estado_TGG` (`Estado_TGG`)) COMMENT='Conceptos Generales de glosas' COLLATE='utf8_general_ci' ENGINE=InnoDB;
CREATE TABLE `cztipoglosaesp` (	`Codigo_TGE` CHAR(2) NOT NULL,	`Descripcion_TGE` VARCHAR(50) NULL,	`Estado_TGE` VARCHAR(50) NULL DEFAULT '1',	PRIMARY KEY (`Codigo_TGE`),	INDEX `Descripcion_TGE` (`Descripcion_TGE`),	INDEX `Estado_TGE` (`Estado_TGE`)) COMMENT='Concepto Especifico Glosas' COLLATE='utf8_general_ci' ENGINE=InnoDB;
CREATE TABLE `cztiposglosas` (	`Codigo_TGG` CHAR(1) NOT NULL,	`Codigo_TGE` CHAR(2) NOT NULL,	`Codigo_TGV` CHAR(3) NULL,	`Descripcion_TGV` VARCHAR(50) NULL,	`Estado_TGV` CHAR(1) NULL DEFAULT '1',	PRIMARY KEY (`Codigo_TGG`, `Codigo_TGE`),	INDEX `Codigo_TGV` (`Codigo_TGV`),	INDEX `Codigo_TGE` (`Codigo_TGE`),	INDEX `Codigo_TGG` (`Codigo_TGG`),	INDEX `Estado_TGV` (`Estado_TGV`)) COMMENT='Tipos de Glosas Validas' COLLATE='utf8_general_ci' ENGINE=InnoDB;
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('1', 'Facturación');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('2', 'Tarifas');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('3', 'Soportes');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('4', 'Autorización');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('5', 'Cobertura');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('6', 'Pertinencia');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('8', 'Devoluciones');
Insert Into cztipoglosagral(Codigo_TGG, Descripcion_TGG) Values ('9', 'Respuestas a glosas o devoluciones');
RENAME TABLE `cztiposglosas` TO `cztipoglosas`;
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('01', 'Estancia');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('02', 'Consultas, interconsultas y visitas médicas');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('03', 'Honorarios médicos en procedimientos');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('04', 'Honorarios otros profesionales asistenciales');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('05', 'Derechos de sala');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('06', 'Materiales');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('07', 'Medicamentos');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('08', 'Ayudas diagnósticas');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('09', 'Atención integral (caso, conjunto integral de atenciones, paquete o grupo
relacionado por diagnóstico)');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('10', 'Servicio o insumo incluido en caso, conjunto integral de atenciones, paquete o grupo
relacionado por diagnóstico');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('11', 'Servicio o insumo incluido en estancia o derechos de sala');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('12', 'Factura excede topes autorizados');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('13', 'Facturar por separado por tipo de recobro (Comité Técnico Científico, (CTC),
accidente de trabajo o enfermedad profesional (ATEP), tutelas)');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('14', 'Error en suma de conceptos facturados');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('15', 'Datos insuficientes del usuario');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('16', 'Usuario o servicio corresponde a otro plan o responsable');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('17', 'Usuario retirado o moroso');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('18', 'Valor en letras diferentes a valor en números');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('19', 'Error en descuento pactado');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('20', 'Recibo de pago compartido');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('21', 'Autorización principal no existe o no corresponde al prestador de servicios de salud');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('22', 'Prescripción dentro de los términos legales o pactados entre las partes');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('23', 'Procedimiento o actividad');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('24', 'Falta firma del prestador de servicios de salud');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('25', 'Examen o actividad pertenece a detección temprana y protección especifica');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('26', 'Usuario o servicio corresponde a capitación');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('27', 'Servicio o procedimiento incluido en otro');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('28', 'Orden cancelada al prestador de servicios de salud');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('29', 'Recargos no pactados');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('30', 'Autorización de servicios adicionales');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('31', 'Bonos o vouchers sin firma del paciente, con enmendaduras o tachones');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('32', 'Detalle de cargos');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('33', 'Copia de historia clínica completa');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('34', 'Resumen de egreso o epicrisis, hoja de atención de urgencias u odontograma');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('35', 'Formato Accidente de trabajo y enfermedad profesional ATEP');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('36', 'Copia de factura o detalle de cargos de seguro obligatorio de accidentes de tránsito
SOAT ');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('37', 'Orden o fórmula médica');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('38', 'Hoja de traslado en ambulancia');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('39', 'Comprobante de recibido del usuario');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('40', 'Registro de anestesia');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('41', 'Descripción quirúrgica');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('42', 'Lista de precios');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('43', 'Orden o autorización de servicios vencida');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('44', 'Profesional que ordena no adscrito');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('45', 'Servicio no pactado');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('46', 'Cobertura sin agotar en la póliza del seguro obligatorio de accidentes de tránsito
SOAT o del FOSYGA ');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('47', 'Faltan soportes de justificación para recobros (Comité Técnico Científico, (CTC),
accidente de trabajo o enfermedad profesional (ATEP), tutelas)');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('48', 'Informe atención inicial de urgencias');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('49', 'Factura no cumple requisitos legales');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('50', 'Factura ya cancelada');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('51', 'Recobro en contrato de capitación por servicios prestados por otro prestador');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('52', 'Disminución en el número de personas incluidas en la capitación');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('53', 'Urgencia no pertinente');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('54', 'Incumplimiento en las metas de cobertura, resolutividad y oportunidad pactadas en
el contrato por capitación');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('96', 'Glosa o devolución injustificada');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('97', 'No subsanada (Glosa o devolución totalmente aceptada)');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('98', 'Subsanada parcial (Glosa o devolución parcialmente aceptada)');
Insert Into cztipoglosaesp(Codigo_TGE, Descripcion_TGE) Values ('99', 'Subsanada (Glosa no aceptada)');
ALTER TABLE `cztipoglosagral`	ADD COLUMN `Respuesta_TGG` CHAR(1) NULL DEFAULT '0' AFTER `Descripcion_TGG`;
UPDATE `cztipoglosagral` SET `Respuesta_TGG`='1' WHERE  `Codigo_TGG`='9';
ALTER TABLE `cztipoglosas`	ADD UNIQUE INDEX `Codigo_TGV_` (`Codigo_TGV`);
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '1', codigo_TGE, Concat('1', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE between '01' and '17';
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '1', codigo_TGE, Concat('1', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('19', '20','22','23','24','25','26','27','28','51','52','54');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '2', codigo_TGE, Concat('2', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE between '01' and '09';
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '2', codigo_TGE, Concat('2', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('23','29');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '3', codigo_TGE, Concat('3', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('01','02','03','04','07','08','09','20','30','31','32','33','35','36','37','38','39','40','41','42','43');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '4', codigo_TGE, Concat('4', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('01','02','06','08','23','30','38','44','43');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '5', codigo_TGE, Concat('5', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('01','02','06','07','08','23','27','45','46');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '6', codigo_TGE, Concat('6', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('01','02','03','04','05','06','07','08','23','53');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '8', codigo_TGE, Concat('8', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('16','17','21','34','44','47','48','49','50');
Insert Into cztipoglosas(Codigo_TGG, Codigo_TGE, Codigo_TGV, Descripcion_TGV) Select '9', codigo_TGE, Concat('9', Codigo_TGE), Descripcion_TGE from cztipoglosaesp where Codigo_TGE in ('96','97','98','99');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('419', '59', '4', '2', 'Conceptos Generales Glosas', 'forms/glosasconcgral.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('420', '59', '4', '2', 'Conceptos Especificos glosas', 'forms/glosasconcesp.php');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('421', '59', '4', '2', 'Conceptos Glosas Aplicables', 'forms/glosasconceptos.php');
UPDATE `ititems` SET `Codigo_ITM`='422' WHERE  `Codigo_ITM`=421 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Codigo_ITM`='421' WHERE  `Codigo_ITM`=420 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Codigo_ITM`='420' WHERE  `Codigo_ITM`=419 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('419', '59', '4', '2', 'Conceptos Glosas');
UPDATE `ititems` SET `Nombre_ITM`='Generales', `Padre_ITM`='419' WHERE  `Codigo_ITM`=420 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Especificos', `Padre_ITM`='419' WHERE  `Codigo_ITM`=421 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Glosas Aplicables', `Padre_ITM`='419' WHERE  `Codigo_ITM`=422 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`) VALUES ('423', '60', '4', '2', 'Recepción de Glosas', 'forms/glosascaptura.php');

ALTER TABLE `ititems`	ADD COLUMN `OptPrinter_ITM` INT(1) UNSIGNED NULL DEFAULT '0' AFTER `Padre_ITM`,	ADD COLUMN `OptNew_ITM` INT(1) UNSIGNED NULL DEFAULT '0' AFTER `OptPrinter_ITM`,	ADD COLUMN `OptNo_ITM` INT(1) UNSIGNED NULL DEFAULT '0' AFTER `OptNew_ITM`,	ADD COLUMN `OpSave_ITM` INT(1) UNSIGNED NULL DEFAULT '1' AFTER `OptNo_ITM`;
