UPDATE `itconfig` SET `Version_DCD`='[VIBRANIUM]20.07.29.001';
CREATE TABLE `hc_GNCOBST` (
	`Codigo_TER` CHAR(10) NOT NULL COLLATE 'latin1_swedish_ci',
	`Codigo_HCF` INT(11) NOT NULL,
	`motivoc_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Motivo Consulta' COLLATE 'utf8_general_ci',
	`enfactual_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Enfermedad Actual' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	INDEX `Codigo_TER` (`Codigo_TER`) USING BTREE,
	INDEX `Codigo_HCF` (`Codigo_HCF`) USING BTREE
)
COMMENT='FORMATO HC GINECO OBSTETRICIA'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `hc_HPRTSN` (
	`Codigo_TER` CHAR(10) NOT NULL COLLATE 'latin1_swedish_ci',
	`Codigo_HCF` INT(11) NOT NULL,
	`motivoc_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Motivo Consulta' COLLATE 'utf8_general_ci',
	`enfactual_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Enfermedad Actual' COLLATE 'utf8_general_ci',
	`cabycue_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Cabeza y Cuello' COLLATE 'utf8_general_ci',
	`torax_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Torax' COLLATE 'utf8_general_ci',
	`abdomen_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Abdomen' COLLATE 'utf8_general_ci',
	`extrem_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Extremidades' COLLATE 'utf8_general_ci',
	`piel_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Piel' COLLATE 'utf8_general_ci',
	`genital_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Genitales' COLLATE 'utf8_general_ci',
	`orgsentidos_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Organos de los Sentidos' COLLATE 'utf8_general_ci',
	`neurolog_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Neurologico' COLLATE 'utf8_general_ci',
	`sistgeneral_HC` TEXT(65535) NULL DEFAULT NULL COMMENT 'Sistema General' COLLATE 'utf8_general_ci',
	`sistresp_HC` TEXT(65535) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sistcardio_HC` TEXT(65535) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sistgastro_HC` TEXT(65535) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sistgenito_HC` TEXT(65535) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	INDEX `Codigo_TER` (`Codigo_TER`) USING BTREE,
	INDEX `Codigo_HCF` (`Codigo_HCF`) USING BTREE
)
COMMENT='FORMATO HC RCV'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `hcidriesgoesp` (
	`Codigo_TER` VARCHAR(10) NOT NULL COLLATE 'utf8_general_ci',
	`Codigo_HCF` INT(11) NOT NULL,
	`Sospcancer_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Sangheces_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Sintresp_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Maltrato_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Vsexual_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Previh_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Pstvih_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	INDEX `Codigo_TER` (`Codigo_TER`) USING BTREE,
	INDEX `Codigo_HCF` (`Codigo_HCF`) USING BTREE
)
COMMENT='Identificacion Riesgos Especificos'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `hcembactual` (
	`Codigo_TER` VARCHAR(10) NOT NULL COLLATE 'utf8_general_ci',
	`Codigo_HCF` INT(11) NOT NULL,
	`Planeado_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Metantc_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Multiple_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Pesoprev_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Talla_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`IMC_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`FUR_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Dudas_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`FPP_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Antitetan_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`FAntitetan_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Intergen_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Gsangre_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`RH_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`RHSensible_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`PreVIH_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Lacmat_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Edadgest_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Numgest_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Fuma_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Cigarr_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Fumpas_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Alcohol_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Drogas_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Notas_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	INDEX `Codigo_TER` (`Codigo_TER`) USING BTREE,
	INDEX `Codigo_HCF` (`Codigo_HCF`) USING BTREE
)
COMMENT='Embarazo Actual'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `hcriegoobs` (
	`Codigo_TER` VARCHAR(10) NOT NULL COLLATE 'utf8_general_ci',
	`Codigo_HCF` INT(11) NOT NULL,
	`Edad_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Paridad_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Aborto_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`RetPlac_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Rnmayor_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Rnmenor_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`HTA_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Gemelar_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Cesprev_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Muerteneo_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Pdificil_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Notas_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C011_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C012_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C013_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C021_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C022_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C023_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C031_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C032_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C033_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C041_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C042_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C043_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C051_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C052_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C053_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C061_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C062_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C063_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C071_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C072_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C073_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C081_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C082_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C083_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C091_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C092_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C093_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C101_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C102_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C103_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C111_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C112_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C113_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C121_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C122_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C123_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C131_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C132_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C133_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C141_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C142_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`C143_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E011_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E012_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E013_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E021_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E022_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E023_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E031_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E032_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E033_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E041_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E042_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E043_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E051_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E052_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E053_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E061_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E062_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E063_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E071_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E072_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E073_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E081_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E082_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E083_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E091_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E092_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E093_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E101_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E102_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E103_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E111_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E112_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E113_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E121_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E122_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`E123_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Punt1T_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Riesgo1T_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Punt2T_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Riesgo2T_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Punt3T_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	`Riesgo3T_HCA` CHAR(1) NULL DEFAULT '0' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	INDEX `Codigo_TER` (`Codigo_TER`) USING BTREE,
	INDEX `Codigo_HCF` (`Codigo_HCF`) USING BTREE
)
COMMENT='Riesgo Obstetrico'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `hcctrlparaobs` (
	`Codigo_TER` VARCHAR(10) NOT NULL COLLATE 'utf8_general_ci',
	`Codigo_HCF` INT(11) NOT NULL,
	`T1R001_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F001_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R001_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F001_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R001_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F001_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R002_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F002_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R002_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F002_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R002_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F002_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R003_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F003_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R003_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F003_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R003_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F003_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R004_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F004_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R004_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F004_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R004_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F004_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R005_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F005_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R005_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F005_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R005_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F005_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R006_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F006_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R006_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F006_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R006_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F006_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R007_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F007_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R007_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F007_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R007_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F007_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R008_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F008_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R008_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F008_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R008_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F008_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R009_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F009_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R009_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F009_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R009_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F009_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R010_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F010_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R010_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F010_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R010_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F010_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R011_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F011_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R011_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F011_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R011_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F011_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R012_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F012_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R012_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F012_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R012_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F012_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R013_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F013_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R013_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F013_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R013_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F013_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R014_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F014_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R014_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F014_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R014_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F014_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R015_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F015_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R015_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F015_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R015_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F015_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R016_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1F016_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T2R016_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2F016_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T3R016_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3F016_HCA` TEXT(65535)   NULL  COLLATE 'utf8_general_ci',
	`T1R017_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2R017_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3R017_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1R018_HCA` CHAR(1) NULL DEFAULT '0'  COLLATE 'utf8_general_ci',
	`T2R018_HCA` CHAR(1) NULL DEFAULT '0'  COLLATE 'utf8_general_ci',
	`T3R018_HCA` CHAR(1) NULL DEFAULT '0'  COLLATE 'utf8_general_ci',
	`T1R019_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2R019_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3R019_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1R020_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2R020_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3R020_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T1R021_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T2R021_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`T3R021_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	`N022_HCA` TEXT(65535)  NULL  COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	INDEX `Codigo_TER` (`Codigo_TER`) USING BTREE,
	INDEX `Codigo_HCF` (`Codigo_HCF`) USING BTREE
)
COMMENT='Control Paraclinicos Obstetricos'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
