UPDATE `itconfig` SET `Version_DCD`='[VIBRANIUM]20.10.22.001';
UPDATE `hcsv2` SET `Sigla_HSV`='TA De Pie', `Prefijo_HSV`='' WHERE  `Codigo_HSV`='11';
UPDATE `hcsv2` SET `Sigla_HSV`='TA Acostado', `Prefijo_HSV`='' WHERE  `Codigo_HSV`='12';
UPDATE `hcsv2` SET `Sigla_HSV`='TA Sentado' WHERE  `Codigo_HSV`='13';
UPDATE `hcsv2` SET `Prefijo_HSV`='' WHERE  `Codigo_HSV`='13';
ALTER TABLE `hctipos`
	ADD COLUMN `EscFramingham_HCT` CHAR(1) NOT NULL DEFAULT '0' AFTER `CtrlPreNat_HCT`;
UPDATE `hctipos` SET `EscFramingham_HCT`='1' WHERE  `Codigo_HCT`='HPRTSN';

ALTER TABLE `hcctrlprentl`
	CHANGE COLUMN `Numero_HCA` `Numero_HCA` INT(11) NOT NULL DEFAULT '0' COMMENT 'Nro de Control' AFTER `Codigo_HCF`,
	CHANGE COLUMN `Fecha_HCA` `Fecha_HCA` DATE NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha' AFTER `Numero_HCA`,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`, `Fecha_HCA`, `Numero_HCA`) USING BTREE;
ALTER TABLE `hcctrlprentl`
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`Codigo_TER`, `Codigo_HCF`) USING BTREE,
	ADD INDEX `Fecha_HCA` (`Fecha_HCA`);
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`, `Padre_ITM`, `OpSave_ITM`) VALUES ('567', '106', '2', '2', 'RIPS US', 'database_table.png', 'reports/rips_us.php', '529', '0');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`, `Padre_ITM`, `OpSave_ITM`) VALUES ('568', '106', '2', '2', 'RIPS AC', 'database_table.png', 'reports/rips_ac.php', '529', '0');
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`, `Subtitle_RPT`, `SQL_RPT`, `Orientacion_RPT`) VALUES ('rips_us', 'Archivo US RIPS', 'Informe entre @FECHA_INICIAL y @FECHA_FINAL ', 'SELECT DISTINCT  d.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, c.Direccion_TER, c.Telefono_TER, c.Correo_TER, a.FechaGraba_CIT, Fecha_AGE, a.FechaDeseada_CIT, k.CUPS_PRC, g.Nombre_ESP \r\nFROM gxcitasmedicas a, gxpacientes b, czterceros c, cztipoid d, gxagendacab e, gxeps f, gxespecialidades g , gxadmision h, gxordenescab i, gxordenesdet j, gxprocedimientos k, gxmedicos l, gxservicios m, gxareas n  \r\nWHERE a.Codigo_TER=b.Codigo_TER AND b.Codigo_TER=c.Codigo_TER AND c.Codigo_TID=d.Codigo_TID AND e.Codigo_AGE=a.Codigo_AGE AND f.Codigo_EPS=b.Codigo_EPS AND g.Codigo_ESP=e.Codigo_ESP  AND h.Codigo_TER=a.Codigo_TER \r\nAND DATE(h.Fecha_ADM)=DATE(a.Fecha_AGE) AND i.Codigo_ADM=h.Codigo_ADM AND i.Codigo_ORD=j.Codigo_ORD AND k.Codigo_SER=j.Codigo_SER\r\nAND l.Codigo_TER=e.Codigo_TER AND i.Codigo_USR=l.Codigo_USR AND m.Codigo_SER=k.Codigo_SER AND m.Codigo_CFC=\'01\' and n.Codigo_ARE=e.Codigo_ARE \r\n AND a.Fecha_AGE BETWEEN \'@FECHA_INICIAL\' AND \'@FECHA_FINAL 23:59:59\' AND f.Codigo_TER=\'@ENTIDAD\' and n.Codigo_SDE=\'@SEDE\';', 'L');
INSERT INTO `itreports` (`Codigo_RPT`, `Descripcion_RPT`, `Subtitle_RPT`, `SQL_RPT`, `Orientacion_RPT`) VALUES ('rips_ac', 'Archivo AC RIPS', 'Informe entre @FECHA_INICIAL y @FECHA_FINAL ', 'SELECT DISTINCT  d.Sigla_TID, c.ID_TER, b.Apellido1_PAC, b.Apellido2_PAC, b.Nombre1_PAC, b.Nombre2_PAC, c.Direccion_TER, c.Telefono_TER, c.Correo_TER, a.FechaGraba_CIT, Fecha_AGE, a.FechaDeseada_CIT, k.CUPS_PRC, g.Nombre_ESP \r\nFROM gxcitasmedicas a, gxpacientes b, czterceros c, cztipoid d, gxagendacab e, gxeps f, gxespecialidades g , gxadmision h, gxordenescab i, gxordenesdet j, gxprocedimientos k, gxmedicos l, gxservicios m, gxareas n  \r\nWHERE a.Codigo_TER=b.Codigo_TER AND b.Codigo_TER=c.Codigo_TER AND c.Codigo_TID=d.Codigo_TID AND e.Codigo_AGE=a.Codigo_AGE AND f.Codigo_EPS=b.Codigo_EPS AND g.Codigo_ESP=e.Codigo_ESP  AND h.Codigo_TER=a.Codigo_TER \r\nAND DATE(h.Fecha_ADM)=DATE(a.Fecha_AGE) AND i.Codigo_ADM=h.Codigo_ADM AND i.Codigo_ORD=j.Codigo_ORD AND k.Codigo_SER=j.Codigo_SER\r\nAND l.Codigo_TER=e.Codigo_TER AND i.Codigo_USR=l.Codigo_USR AND m.Codigo_SER=k.Codigo_SER AND m.Codigo_CFC=\'01\' and n.Codigo_ARE=e.Codigo_ARE \r\n AND a.Fecha_AGE BETWEEN \'@FECHA_INICIAL\' AND \'@FECHA_FINAL 23:59:59\' AND f.Codigo_TER=\'@ENTIDAD\' and n.Codigo_SDE=\'@SEDE\';', 'L');
UPDATE `itreports` SET `SQL_RPT`='SELECT Sigla_TID, ID_TER, \'\', Codigo_PLA, Nombre1_PAC, Nombre2_PAC, Apellido1_PAC, Apellido2_PAC, FechaNac_PAC, \'\', Codigo_SEX, Codigo_DEP, Codigo_MUN\r\nFROM gxpacientes a, czterceros b, hcfolios d, cztipoid c\r\nWHERE a.Codigo_TER=b.Codigo_TER AND d.Codigo_TER=b.Codigo_TER AND c.Codigo_TID=b.Codigo_TID\r\nAND d.Fecha_HCF >= \'@FECHA_INICIAL\' AND d.Fecha_HCF <= \'@FECHA_FINAL 23:59:59\' AND a.Codigo_EPS=\'@ENTIDAD\'\r\n' WHERE  `Codigo_RPT`='rips_us' AND `Codigo_DCD`=0;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('rips_us', 'FECHA_FINAL', 'Fecha Final', '3', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('rips_us', 'FECHA_INICIAL', 'Fecha Inicial', '2', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('rips_us', 'EPS', 'Contrato', '4', 'S');
UPDATE `itreportsparam` SET `Campo_RPT`='ENTIDAD' WHERE  `Codigo_RPT`='rips_us' AND `Campo_RPT`='EPS' AND `Codigo_DCD`=0;
INSERT INTO `itreportsselects` (`Codigo_RPT`, `Campo_RPT`, `Consulta_RPT`) VALUES ('rips_us', 'ENTIDAD', 'Select Codigo_eps, Nombre_eps from gxeps  Order By 2;');
UPDATE `itreports` SET `SQL_RPT`='SELECT DISTINCT Sigla_TID, ID_TER, \'\', Codigo_PLA, Nombre1_PAC, Nombre2_PAC, Apellido1_PAC, Apellido2_PAC, FechaNac_PAC, \'\', Codigo_SEX, Codigo_DEP, Codigo_MUN\r\nFROM gxpacientes a, czterceros b, hcfolios d, cztipoid c\r\nWHERE a.Codigo_TER=b.Codigo_TER AND d.Codigo_TER=b.Codigo_TER AND c.Codigo_TID=b.Codigo_TID\r\nAND d.Fecha_HCF >= \'@FECHA_INICIAL\' AND d.Fecha_HCF <= \'@FECHA_FINAL 23:59:59\' AND a.Codigo_EPS=\'@ENTIDAD\'\r\n' WHERE  `Codigo_RPT`='rips_us' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='SELECT distinct \'\', \'\', Sigla_TID, ID_TER, Fecha_HCF, \'\', Nombre_ESP, \'\', \'\', Codigo_DGN, CodigoR_DGN\r\nFROM gxpacientes a, czterceros b, hcfolios d, cztipoid c, hcdiagnosticos h, gxespecialidades i, gxmedicos j, gxmedicosesp k\r\nWHERE a.Codigo_TER=b.Codigo_TER AND d.Codigo_TER=b.Codigo_TER AND c.Codigo_TID=b.Codigo_TID AND i.Codigo_ESP=k.Codigo_ESP AND k.Codigo_TER=j.Codigo_TER\r\nAND h.Codigo_TER=b.Codigo_TER AND h.Codigo_HCF=d.Codigo_HCF AND j.Codigo_USR=d.Codigo_USR\r\nAND d.Fecha_HCF >= \'@FECHA_INICIAL\' AND d.Fecha_HCF <= \'@FECHA_FINAL 23:59:59\' AND a.Codigo_EPS=\'@ENTIDAD\'\r\n' WHERE  `Codigo_RPT`='rips_ac' AND `Codigo_DCD`=0;
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('rips_ac', 'ENTIDAD', 'Contrato', '4', 'S');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('rips_ac', 'FECHA_FINAL', 'Fecha Final', '3', 'D');
INSERT INTO `itreportsparam` (`Codigo_RPT`, `Campo_RPT`, `Titulo_RPT`, `Orden_RPT`, `Tipo_RPT`) VALUES ('rips_ac', 'FECHA_INICIAL', 'Fecha Inicial', '2', 'D');
INSERT INTO `itreportsselects` (`Codigo_RPT`, `Campo_RPT`, `Consulta_RPT`) VALUES ('rips_ac', 'ENTIDAD', 'Select Codigo_eps, Nombre_eps from gxeps  Order By 2;');
UPDATE `itreports` SET `SQL_RPT`='SELECT distinct \'\', \'\', Sigla_TID, ID_TER, Fecha_HCF, \'\', Nombre_ESP, \'\', \'\', Codigo_DGN, CodigoR_DGN\r\nFROM gxpacientes a, czterceros b, cztipoid c,  gxespecialidades i, gxmedicos j, gxmedicosesp k,\r\n hcfolios d LEFT JOIN hcdiagnosticos h ON h.Codigo_TER=b.Codigo_TER AND h.Codigo_HCF=d.Codigo_HCF\r\nWHERE a.Codigo_TER=b.Codigo_TER AND d.Codigo_TER=b.Codigo_TER AND c.Codigo_TID=b.Codigo_TID AND i.Codigo_ESP=k.Codigo_ESP AND k.Codigo_TER=j.Codigo_TER\r\n AND j.Codigo_USR=d.Codigo_USR\r\nAND d.Fecha_HCF >= \'@FECHA_INICIAL\' AND d.Fecha_HCF <= \'@FECHA_FINAL 23:59:59\' AND a.Codigo_EPS=\'@ENTIDAD\'\r\n' WHERE  `Codigo_RPT`='rips_ac' AND `Codigo_DCD`=0;
UPDATE `itreports` SET `SQL_RPT`='SELECT distinct \'\', \'\', Sigla_TID, ID_TER, Fecha_HCF, \'\', Nombre_ESP, \'\', \'\', Codigo_DGN, CodigoR_DGN\r\nFROM gxpacientes a, czterceros b, cztipoid c,  gxespecialidades i, gxmedicos j, gxmedicosesp k,\r\n hcfolios d LEFT JOIN hcdiagnosticos h ON h.Codigo_TER=d.Codigo_TER AND h.Codigo_HCF=d.Codigo_HCF\r\nWHERE a.Codigo_TER=b.Codigo_TER AND d.Codigo_TER=b.Codigo_TER AND c.Codigo_TID=b.Codigo_TID AND i.Codigo_ESP=k.Codigo_ESP AND k.Codigo_TER=j.Codigo_TER\r\n AND j.Codigo_USR=d.Codigo_USR\r\nAND d.Fecha_HCF >= \'@FECHA_INICIAL\' AND d.Fecha_HCF <= \'@FECHA_FINAL 23:59:59\' AND a.Codigo_EPS=\'@ENTIDAD\'\r\n' WHERE  `Codigo_RPT`='rips_ac' AND `Codigo_DCD`=0;
ALTER TABLE `hcdiagnosticos`
	CHANGE COLUMN `Tipo_DGN` `Tipo_DGN` VARCHAR(20) NULL DEFAULT '1' COLLATE 'utf8_general_ci' AFTER `CodigoR3_DGN`;

ALTER TABLE `hctipos`
	ADD COLUMN `Icono_HCT` VARCHAR(30) NOT NULL DEFAULT 'GenomaX' AFTER `SexoF_HCT`;
UPDATE `hctipos` SET `Icono_HCT`='apple' WHERE  `Codigo_HCT`='NNUTRI';
UPDATE `hctipos` SET `Icono_HCT`='brain_trainer' WHERE  `Codigo_HCT`='NPSICO';
UPDATE `hctipos` SET `Icono_HCT`='brain_trainer' WHERE  `Codigo_HCT`='HCPSC';
UPDATE `hctipos` SET `Icono_HCT`='health' WHERE  `Codigo_HCT`='EVOL2';
