UPDATE `nxs_gnx`.`itaplicaciones` SET `Nombre_APP`='Nexus' WHERE  `Codigo_APP`=3;
UPDATE `nxs_gnx`.`itmodulos` SET `Nombre_MOD`='Asistencial', `Descripcion_MOD`='Asistencial' WHERE  `Codigo_MOD`=2 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Nombre_MOD`='Administrativo', `Descripcion_MOD`='Administrativo' WHERE  `Codigo_MOD`=3 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=7 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=9 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=10 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=11 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=12 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=13 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=14 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=15 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=16 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=5 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=4 AND `Codigo_APP`=1;
ALTER TABLE `gnxconect`
	ADD COLUMN `Codigo_APP` INT(2) NULL DEFAULT '2' AFTER `DB_NAME`;
INSERT INTO `nxs_gnx`.`gnxconect` (`CODE_NAME`, `DB_NAME`, `Codigo_APP`) VALUES ('_md', 'md', '1');
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=5 AND `Codigo_APP`=1 AND `Codigo_MOD`=1;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=4 AND `Codigo_APP`=1 AND `Codigo_MOD`=1;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=3 AND `Codigo_APP`=1 AND `Codigo_MOD`=1;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=2 AND `Codigo_APP`=1 AND `Codigo_MOD`=1;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=1 AND `Codigo_APP`=1 AND `Codigo_MOD`=1;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=7 AND `Codigo_APP`=1 AND `Codigo_MOD`=3;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=8 AND `Codigo_APP`=1 AND `Codigo_MOD`=3;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=11 AND `Codigo_APP`=1 AND `Codigo_MOD`=2;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=12 AND `Codigo_APP`=1 AND `Codigo_MOD`=2;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=26 AND `Codigo_APP`=1 AND `Codigo_MOD`=10;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=27 AND `Codigo_APP`=1 AND `Codigo_MOD`=10;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=28 AND `Codigo_APP`=1 AND `Codigo_MOD`=10;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=38 AND `Codigo_APP`=1 AND `Codigo_MOD`=9;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=39 AND `Codigo_APP`=1 AND `Codigo_MOD`=9;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=40 AND `Codigo_APP`=1 AND `Codigo_MOD`=9;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=56 AND `Codigo_APP`=1 AND `Codigo_MOD`=4;
UPDATE `nxs_gnx`.`itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=5 AND `Codigo_APP`=1 AND `Codigo_MOD`=1;
UPDATE `nxs_gnx`.`itmenu` SET `Codigo_MOD`='3' WHERE  `Codigo_MNU`=10 AND `Codigo_APP`=1 AND `Codigo_MOD`=2;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='1' WHERE  `Codigo_MNU`=5 AND `Codigo_APP`=1 AND `Codigo_MOD`=2;
UPDATE `nxs_gnx`.`itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=6 AND `Codigo_APP`=1 AND `Codigo_MOD`=3;
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Icono_ITM`, `Enlace_ITM`) VALUES ('599', '97', '2', '2', 'Devolucion', 'large_tiles.png', 'forms/invdevol.php');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('600', '5', '2', '1', 'Agenda', 'forms/md_schedule.php', '0');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('601', '5', '2', '1', 'Atención', 'forms/md_medicalrec.php', '0');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('602', '6', '3', '1', 'Caja', 'forms/md_cash.php', '0');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('603', '6', '3', '1', 'Facturación', 'forms/md_invoice.php', '0');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('604', '6', '3', '1', 'Cartera', 'forms/md_charges.php', '0');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('605', '6', '3', '1', 'Contabilidad', 'forms/md_accounting.php', '0');
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('606', '6', '3', '1', 'Contabilidad', 'forms/md_accounting.php', '0');
UPDATE `nxs_gnx`.`ititems` SET `Nombre_ITM`='Reportes', `Enlace_ITM`='forms/md_reports.php' WHERE  `Codigo_ITM`=606 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
INSERT INTO `nxs_gnx`.`ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`, `Enlace_ITM`, `OpSave_ITM`) VALUES ('607', '6', '3', '1', 'Configuración', 'forms/md_config.php', '0');
UPDATE `nxs_gnx`.`ititems` SET `Codigo_MNU`='10' WHERE  `Codigo_ITM`=602 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`ititems` SET `Codigo_MNU`='10' WHERE  `Codigo_ITM`=603 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`ititems` SET `Codigo_MNU`='10' WHERE  `Codigo_ITM`=604 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`ititems` SET `Codigo_MNU`='10' WHERE  `Codigo_ITM`=605 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`ititems` SET `Codigo_MNU`='10' WHERE  `Codigo_ITM`=606 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
UPDATE `nxs_gnx`.`ititems` SET `Codigo_MNU`='10' WHERE  `Codigo_ITM`=607 AND `Codigo_MNU`=6 AND `Codigo_MOD`=3 AND `Codigo_APP`=1;
INSERT INTO `nxs_gnx`.`gnxconect` (`CODE_NAME`, `DB_PREFIX`, `DB_NAME`, `Codigo_APP`) VALUES ('klud', 'kld_', 'axis', '3');
INSERT INTO `nxs_gnx`.`itaplicaciones` (`Codigo_APP`, `Nombre_APP`, `Version_APP`) VALUES ('4', 'K´lud', 'Travellers');
UPDATE `nxs_gnx`.`itaplicaciones` SET `Codigo_APP`='10' WHERE  `Codigo_APP`=4;
UPDATE `nxs_gnx`.`gnxconect` SET `Codigo_APP`='10' WHERE  `CODE_NAME`='klud';
UPDATE `nxs_gnx`.`ititems` SET `Nombre_ITM`='DB NeXuS', `Icono_ITM`='database_table.png', `Enlace_ITM`='forms/masterdb.php' WHERE  `Codigo_ITM`=140 AND `Codigo_MNU`=14 AND `Codigo_MOD`=0 AND `Codigo_APP`=0;
ALTER TABLE `ittables`
	CHANGE COLUMN `NameShow_TBL` `NameShow_TBL` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_general_ci' FIRST;
