ALTER TABLE `itconfig`	CHANGE COLUMN `Version_DCD` `Version_DCD` VARCHAR(40) NULL DEFAULT NULL AFTER `Updatelink_DCD`;
UPDATE `itconfig` SET `Version_DCD`='[VIBRANIUM]19.05.20.001';
UPDATE `itmodulos` SET `Icono_MOD`='nexus-it.co' WHERE  `Codigo_MOD`=0 AND `Codigo_APP`=0;
UPDATE `itmodulos` SET `Descripcion_MOD`='Parametros Nexus-it Apps Systems' WHERE  `Codigo_MOD`=0 AND `Codigo_APP`=0;
UPDATE `itmodulos` SET `Nombre_MOD`='Administrativo' WHERE  `Codigo_MOD`=1 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Nombre_MOD`='Asistencial' WHERE  `Codigo_MOD`=2 AND `Codigo_APP`=2;
ALTER TABLE `itmenu`	ADD COLUMN `FontLogo_MNU` VARCHAR(50) NOT NULL DEFAULT 'fa fa-cog' AFTER `Descripcion_MNU`;
UPDATE `itmodulos` SET `Descripcion_MOD`='Modulos Administrativos' WHERE  `Codigo_MOD`=1 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Descripcion_MOD`='Modulos Asistenciales' WHERE  `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=3 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=5 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=8 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `itmodulos` SET `Activo_MOD`='0' WHERE  `Codigo_MOD`=19 AND `Codigo_APP`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Configuración' WHERE  `Codigo_MNU`=13 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itmenu` SET `Nombre_MNU`='Utilidades' WHERE  `Codigo_MNU`=14 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `ititems` SET `Codigo_MNU`='14' WHERE  `Codigo_ITM`=470 AND `Codigo_MNU`=15 AND `Codigo_MOD`=0 AND `Codigo_APP`=0;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-sliders' WHERE  `Codigo_MNU`=13 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-cogs' WHERE  `Codigo_MNU`=14 AND `Codigo_APP`=0 AND `Codigo_MOD`=0;
UPDATE `itmenu` SET `Nombre_MNU`='Gerencial' WHERE  `Codigo_MNU`=44 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Nombre_MNU`='Gerencial' WHERE  `Codigo_MNU`=45 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Nombre_MNU`='Gerencial' WHERE  `Codigo_MNU`=46 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Nombre_MNU`='Admisiones' WHERE  `Codigo_MNU`=47 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Admisiones' WHERE  `Codigo_MNU`=48 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Admisiones' WHERE  `Codigo_MNU`=49 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Facturación' WHERE  `Codigo_MNU`=50 AND `Codigo_APP`=2 AND `Codigo_MOD`=3;
UPDATE `itmenu` SET `Nombre_MNU`='Facturación' WHERE  `Codigo_MNU`=51 AND `Codigo_APP`=2 AND `Codigo_MOD`=3;
UPDATE `itmenu` SET `Nombre_MNU`='Facturación' WHERE  `Codigo_MNU`=52 AND `Codigo_APP`=2 AND `Codigo_MOD`=3;
UPDATE `itmenu` SET `Nombre_MNU`='Cartera' WHERE  `Codigo_MNU`=59 AND `Codigo_APP`=2 AND `Codigo_MOD`=4;
UPDATE `itmenu` SET `Nombre_MNU`='Cartera' WHERE  `Codigo_MNU`=60 AND `Codigo_APP`=2 AND `Codigo_MOD`=4;
UPDATE `itmenu` SET `Nombre_MNU`='Cartera' WHERE  `Codigo_MNU`=61 AND `Codigo_APP`=2 AND `Codigo_MOD`=4;
UPDATE `itmenu` SET `Nombre_MNU`='Farmacia' WHERE  `Codigo_MNU`=97 AND `Codigo_APP`=2 AND `Codigo_MOD`=5;
UPDATE `itmenu` SET `Nombre_MNU`='Farmacia' WHERE  `Codigo_MNU`=98 AND `Codigo_APP`=2 AND `Codigo_MOD`=5;
UPDATE `itmenu` SET `Nombre_MNU`='Farmacia' WHERE  `Codigo_MNU`=99 AND `Codigo_APP`=2 AND `Codigo_MOD`=5;
UPDATE `itmenu` SET `Nombre_MNU`='Historias Clínicas' WHERE  `Codigo_MNU`=91 AND `Codigo_APP`=2 AND `Codigo_MOD`=6;
UPDATE `itmenu` SET `Nombre_MNU`='Historias Clínicas' WHERE  `Codigo_MNU`=92 AND `Codigo_APP`=2 AND `Codigo_MOD`=6;
UPDATE `itmenu` SET `Nombre_MNU`='Historias Clínicas' WHERE  `Codigo_MNU`=93 AND `Codigo_APP`=2 AND `Codigo_MOD`=6;
UPDATE `itmenu` SET `Nombre_MNU`='Gestión Humana' WHERE  `Codigo_MNU`=94 AND `Codigo_APP`=2 AND `Codigo_MOD`=7;
UPDATE `itmenu` SET `Nombre_MNU`='Gestión Humana' WHERE  `Codigo_MNU`=95 AND `Codigo_APP`=2 AND `Codigo_MOD`=7;
UPDATE `itmenu` SET `Nombre_MNU`='Gestión Humana' WHERE  `Codigo_MNU`=96 AND `Codigo_APP`=2 AND `Codigo_MOD`=7;
UPDATE `itmenu` SET `Nombre_MNU`='Tesorería' WHERE  `Codigo_MNU`=103 AND `Codigo_APP`=2 AND `Codigo_MOD`=8;
UPDATE `itmenu` SET `Nombre_MNU`='Tesorería' WHERE  `Codigo_MNU`=104 AND `Codigo_APP`=2 AND `Codigo_MOD`=8;
UPDATE `itmenu` SET `Nombre_MNU`='Tesorería' WHERE  `Codigo_MNU`=105 AND `Codigo_APP`=2 AND `Codigo_MOD`=8;
UPDATE `itmenu` SET `Nombre_MNU`='Contabilidad' WHERE  `Codigo_MNU`=53 AND `Codigo_APP`=2 AND `Codigo_MOD`=17;
UPDATE `itmenu` SET `Nombre_MNU`='Contabilidad' WHERE  `Codigo_MNU`=54 AND `Codigo_APP`=2 AND `Codigo_MOD`=17;
UPDATE `itmenu` SET `Nombre_MNU`='Contabilidad' WHERE  `Codigo_MNU`=55 AND `Codigo_APP`=2 AND `Codigo_MOD`=17;
UPDATE `itmenu` SET `Nombre_MNU`='Citas Médicas' WHERE  `Codigo_MNU`=100 AND `Codigo_APP`=2 AND `Codigo_MOD`=18;
UPDATE `itmenu` SET `Nombre_MNU`='Citas Médicas' WHERE  `Codigo_MNU`=101 AND `Codigo_APP`=2 AND `Codigo_MOD`=18;
UPDATE `itmenu` SET `Nombre_MNU`='Citas Médicas' WHERE  `Codigo_MNU`=102 AND `Codigo_APP`=2 AND `Codigo_MOD`=18;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=50 AND `Codigo_APP`=2 AND `Codigo_MOD`=3;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=51 AND `Codigo_APP`=2 AND `Codigo_MOD`=3;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=52 AND `Codigo_APP`=2 AND `Codigo_MOD`=3;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=97 AND `Codigo_APP`=2 AND `Codigo_MOD`=5;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=98 AND `Codigo_APP`=2 AND `Codigo_MOD`=5;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=99 AND `Codigo_APP`=2 AND `Codigo_MOD`=5;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=91 AND `Codigo_APP`=2 AND `Codigo_MOD`=6;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=59 AND `Codigo_APP`=2 AND `Codigo_MOD`=4;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=60 AND `Codigo_APP`=2 AND `Codigo_MOD`=4;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=92 AND `Codigo_APP`=2 AND `Codigo_MOD`=6;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=93 AND `Codigo_APP`=2 AND `Codigo_MOD`=6;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=100 AND `Codigo_APP`=2 AND `Codigo_MOD`=18;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=101 AND `Codigo_APP`=2 AND `Codigo_MOD`=18;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=102 AND `Codigo_APP`=2 AND `Codigo_MOD`=18;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=106 AND `Codigo_APP`=2 AND `Codigo_MOD`=19;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=107 AND `Codigo_APP`=2 AND `Codigo_MOD`=19;
UPDATE `itmenu` SET `Codigo_MOD`='2' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=2 AND `Codigo_MOD`=19;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=59 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=60 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=61 AND `Codigo_APP`=2 AND `Codigo_MOD`=4;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=94 AND `Codigo_APP`=2 AND `Codigo_MOD`=7;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=95 AND `Codigo_APP`=2 AND `Codigo_MOD`=7;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=96 AND `Codigo_APP`=2 AND `Codigo_MOD`=7;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=103 AND `Codigo_APP`=2 AND `Codigo_MOD`=8;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=104 AND `Codigo_APP`=2 AND `Codigo_MOD`=8;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=105 AND `Codigo_APP`=2 AND `Codigo_MOD`=8;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=53 AND `Codigo_APP`=2 AND `Codigo_MOD`=17;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=54 AND `Codigo_APP`=2 AND `Codigo_MOD`=17;
UPDATE `itmenu` SET `Codigo_MOD`='1' WHERE  `Codigo_MNU`=55 AND `Codigo_APP`=2 AND `Codigo_MOD`=17;
UPDATE `itmenu` SET `Nombre_MNU`='Calidad y Estadística' WHERE  `Codigo_MNU`=106 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Calidad y Estadística' WHERE  `Codigo_MNU`=107 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Calidad y Estadística' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=45 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=46 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=48 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=49 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=51 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=52 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=60 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=61 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=98 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=99 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=92 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=93 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=95 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=96 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=104 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=105 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=54 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=55 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=101 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=102 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=107 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Activo_MNU`='0' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-briefcase' WHERE  `Codigo_MNU`=59 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-bar-chart ' WHERE  `Codigo_MNU`=106 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-users' WHERE  `Codigo_MNU`=94 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-line-chart' WHERE  `Codigo_MNU`=44 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-stethoscope' WHERE  `Codigo_MNU`=91 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-medkit' WHERE  `Codigo_MNU`=97 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-briefcase' WHERE  `Codigo_MNU`=59 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-bar-chart ' WHERE  `Codigo_MNU`=106 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-users' WHERE  `Codigo_MNU`=94 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-line-chart' WHERE  `Codigo_MNU`=44 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-stethoscope' WHERE  `Codigo_MNU`=91 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-medkit' WHERE  `Codigo_MNU`=97 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-calculator' WHERE  `Codigo_MNU`=50 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-money' WHERE  `Codigo_MNU`=103 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-money' WHERE  `Codigo_MNU`=53 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `FontLogo_MNU`='glyphicon glyphicon-piggy-bank' WHERE  `Codigo_MNU`=103 AND `Codigo_APP`=2 AND `Codigo_MOD`=1;
UPDATE `itmenu` SET `Nombre_MNU`='Laboratorio', `FontLogo_MNU`='fa fa-flask', `Activo_MNU`='1' WHERE  `Codigo_MNU`=107 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `Nombre_MNU`='Imágenes Diagnósticas', `Activo_MNU`='1' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='fa fa-heartbeat' WHERE  `Codigo_MNU`=108 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE `itmenu` SET `FontLogo_MNU`='glyphicon glyphicon-log-in' WHERE  `Codigo_MNU`=47 AND `Codigo_APP`=2 AND `Codigo_MOD`=2;
UPDATE ititems SET codigo_mnu=44, codigo_mod=1 WHERE codigo_app=2 AND codigo_mnu in (44,45,46);
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('486', '47', '2', '2', 'Utilidades');
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=466 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=443 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=370 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=369 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=331 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=330 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='486' WHERE  `Codigo_ITM`=329 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=47, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu IN (47,48,49);
UPDATE `ititems` SET `Padre_ITM`='322' WHERE  `Codigo_ITM`=328 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='322' WHERE  `Codigo_ITM`=432 AND `Codigo_MNU`=47 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Reimpresión' WHERE  `Codigo_ITM`=292 AND `Codigo_MNU`=51 AND `Codigo_MOD`=3 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('487', '50', '2', '2', 'Reportes');
UPDATE ititems SET Padre_ITM=487, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu IN (52);
UPDATE ititems SET codigo_mnu=50, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu in (50,51,52);
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('488', '50', '2', '2', 'Configuración');
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('489', '50', '2', '2', 'Utilidades');
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=317 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=405 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=291 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=290 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=289 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=288 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=287 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=286 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=285 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=284 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=283 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=282 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=281 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=280 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=279 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=278 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='488' WHERE  `Codigo_ITM`=277 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=365 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=364 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=320 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=319 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=318 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=473 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=431 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='489' WHERE  `Codigo_ITM`=294 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Liquidar Contratos Capitados' WHERE  `Codigo_ITM`=459 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Liquidar Cuentas Grupal' WHERE  `Codigo_ITM`=463 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Editar Ingresos Facturados' WHERE  `Codigo_ITM`=431 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Resolución Facturación', `Padre_ITM`='488' WHERE  `Codigo_ITM`=473 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Anular Ordenes de Servicio' WHERE  `Codigo_ITM`=298 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Anular Facturas' WHERE  `Codigo_ITM`=299 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Liquidar Contrato Capitado' WHERE  `Codigo_ITM`=459 AND `Codigo_MNU`=50 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('490', '1', '2', 'Configuración');
UPDATE `ititems` SET `Codigo_ITM`='490', `Codigo_MNU`='60' WHERE  `Codigo_ITM`=0 AND `Codigo_MNU`=490 AND `Codigo_MOD`=1 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='490' WHERE  `Codigo_ITM`=404 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='490' WHERE  `Codigo_ITM`=419 AND `Codigo_MNU`=59 AND `Codigo_MOD`=4 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=59, codigo_mod=1 WHERE codigo_app=2 AND codigo_mnu in (59,60,61);
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('491', '91', '2', '2', 'Configuración');
UPDATE `ititems` SET `Padre_ITM`='491' WHERE  `Codigo_ITM`=366 AND `Codigo_MNU`=91 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='491' WHERE  `Codigo_ITM`=367 AND `Codigo_MNU`=91 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='491' WHERE  `Codigo_ITM`=368 AND `Codigo_MNU`=91 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='491' WHERE  `Codigo_ITM`=369 AND `Codigo_MNU`=91 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('492', '91', '2', '2', 'Utilidades');
UPDATE `ititems` SET `Padre_ITM`='492' WHERE  `Codigo_ITM`=435 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='492' WHERE  `Codigo_ITM`=472 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='492' WHERE  `Codigo_ITM`=378 AND `Codigo_MNU`=92 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='492' WHERE  `Codigo_ITM`=485 AND `Codigo_MNU`=93 AND `Codigo_MOD`=6 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=91, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu in (91,92,93);
UPDATE `ititems` SET `Nombre_ITM`='Listado PreTriage' WHERE  `Codigo_ITM`=480 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('493', '91', '2', '2', 'Reimpresión');
UPDATE `ititems` SET `Nombre_ITM`='Reimpresión y Reportes' WHERE  `Codigo_ITM`=493 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=464 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=382 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=381 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=379 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Triage' WHERE  `Codigo_ITM`=371 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='371' WHERE  `Codigo_ITM`=372 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='371' WHERE  `Codigo_ITM`=480 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='371' WHERE  `Codigo_ITM`=481 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='371' WHERE  `Codigo_ITM`=483 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=394 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=455 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=465 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Resultados Imagenología' WHERE  `Codigo_ITM`=377 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Pacientes por Periodo' WHERE  `Codigo_ITM`=455 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Tratamientos por Area' WHERE  `Codigo_ITM`=465 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Tipos Historias Clínicas' WHERE  `Codigo_ITM`=366 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Nombre_ITM`='Encabezados HC' WHERE  `Codigo_ITM`=367 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=376 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=377 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='493' WHERE  `Codigo_ITM`=400 AND `Codigo_MNU`=91 AND `Codigo_MOD`=2 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('494', '94', '1', '2', 'Configuración');
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=341 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=342 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=343 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=344 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=345 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=346 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=347 AND `Codigo_MNU`=94 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('495', '94', '1', '2', 'Reimpresión y Reportes');
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=349 AND `Codigo_MNU`=96 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=350 AND `Codigo_MNU`=96 AND `Codigo_MOD`=7 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=94, codigo_mod=1 WHERE codigo_app=2 AND codigo_mnu in (94,95,96);
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('494', '97', '1', '2', 'Configuración');
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=353 AND `Codigo_MNU`=97 AND `Codigo_MOD`=5 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=354 AND `Codigo_MNU`=97 AND `Codigo_MOD`=5 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='494' WHERE  `Codigo_ITM`=361 AND `Codigo_MNU`=97 AND `Codigo_MOD`=5 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=97, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu in (97,98,99);
UPDATE `ititems` SET `Nombre_ITM`='Reimpresión y Reportes' WHERE  `Codigo_ITM`=436 AND `Codigo_MNU`=101 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
INSERT INTO `ititems` (`Codigo_ITM`, `Codigo_MNU`, `Codigo_MOD`, `Codigo_APP`, `Nombre_ITM`) VALUES ('495', '100', '2', '2', 'Configuración');
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=383 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=384 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=474 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=475 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=476 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=477 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='495' WHERE  `Codigo_ITM`=424 AND `Codigo_MNU`=100 AND `Codigo_MOD`=18 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=100, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu in (100,101,102);
UPDATE `ititems` SET `Nombre_ITM`='Reimpresión y Reportes' WHERE  `Codigo_ITM`=445 AND `Codigo_MNU`=104 AND `Codigo_MOD`=8 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='445' WHERE  `Codigo_ITM`=452 AND `Codigo_MNU`=105 AND `Codigo_MOD`=8 AND `Codigo_APP`=2;
UPDATE `ititems` SET `Padre_ITM`='445' WHERE  `Codigo_ITM`=451 AND `Codigo_MNU`=105 AND `Codigo_MOD`=8 AND `Codigo_APP`=2;
UPDATE ititems SET codigo_mnu=103, codigo_mod=1 WHERE codigo_app=2 AND codigo_mnu in (103,104,105);
UPDATE ititems SET codigo_mnu=106, codigo_mod=2 WHERE codigo_app=2 AND codigo_mnu in (106,107,108);
CREATE TABLE `gxgruposetareos` (	`Codigo_ETA` CHAR(2) NOT NULL,	`Nombre_ETA` VARCHAR(50) NULL,	`Min_ETA` INT NOT NULL DEFAULT '0',	`Max_ETA` INT NOT NULL DEFAULT '150',	`Tipo_ETA` ENUM('DAY','MONTH','YEAR') NULL DEFAULT 'YEAR',	PRIMARY KEY (`Codigo_ETA`),	UNIQUE INDEX `Nombre1_ETA` (`Nombre_ETA`),	INDEX `Nombre_ETA` (`Nombre_ETA`),	INDEX `Min_ETA_Max_ETA` (`Min_ETA`, `Max_ETA`)) COLLATE='utf8_general_ci' ENGINE=INNODB;
INSERT INTO `gxgruposetareos` (`Codigo_ETA`, `Nombre_ETA`, `Max_ETA`) VALUES ('0', 'Primera Infancia (0-5 años)', '5');
INSERT INTO `gxgruposetareos` (`Codigo_ETA`, `Nombre_ETA`, `Min_ETA`, `Max_ETA`) VALUES ('1', 'Infancia (6 - 11 años)', '6', '11');
INSERT INTO `gxgruposetareos` (`Codigo_ETA`, `Nombre_ETA`, `Min_ETA`, `Max_ETA`) VALUES ('2', 'Adolescencia (12 - 18 años)', '12', '18');
INSERT INTO `gxgruposetareos` (`Codigo_ETA`, `Nombre_ETA`, `Min_ETA`, `Max_ETA`) VALUES ('3', 'Juventud (19 - 26 años)', '19', '26');
INSERT INTO `gxgruposetareos` (`Codigo_ETA`, `Nombre_ETA`, `Min_ETA`, `Max_ETA`) VALUES ('4', 'Adultez (27- 59 años)', '27', '59');
INSERT INTO `gxgruposetareos` (`Codigo_ETA`, `Nombre_ETA`, `Min_ETA`) VALUES ('5', 'Persona Mayor (60 años o mas) ', '60');
